#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
黄州（3篇扩充至11篇）、杭州（8篇扩充至10篇）苏轼真实名篇定义
"""

HUANGZHOU_EXPAND_WORKS = [
    {
        "id": "work_houchibi_fu",
        "title": "后赤壁赋",
        "genre": "赋",
        "station_ids": ["station_huangzhou"],
        "creation_context": "元丰五年十月十五日，苏轼与二客重游黄州赤壁，霜露既降木叶尽脱，再作名赋。",
        "why_related": "与前赤壁赋并称双璧，水落石出、孤鹤横江，完成了向宇宙更深层次的探寻与超拔。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元丰五年（1082）十月十五日",
        "place_label": "黄州赤壁下江心",
        "lead_quote": "霜露既降，木叶尽脱，人影在地，仰见明月。山高月小，水落石出。曾日月之几何，而江山不可复识矣。",
        "lead_guide": "山高月小，水落石出。冬夜重访赤壁，苏轼在孤峭幽绝的江山中感悟时空变幻与精神飞升。",
        "life_background": "初冬时节，苏轼携妇人所藏斗酒，与客再次泛舟赤壁矶下。登临断岸拔丛木，见孤鹤横江东来。",
        "original_text": "是岁十月之望，步自雪堂，将归于临皋。二客从予过黄泥之坂。霜露既降，木叶尽脱，人影在地，仰见明月，顾而乐之，行歌相答。\n于是携酒与鱼，复游于赤壁之下。江流有声，断岸千尺；山高月小，水落石出。曾日月之几何，而江山不可复识矣！\n时夜将半，四顾寂寥。适有孤鹤，横江东来。翅如车轮，玄裳缟衣，戛然长鸣，掠予舟而西也。",
        "why_at_this_moment": "从盛夏的随喜豁达，走向深冬的冷峻空灵，展现东坡生命哲思的深邃多面。",
        "how_it_responds": "以道家化鹤归梦的超脱想象，冲决人世的短暂拘囿。",
        "modern_meaning": "时间会改变许多东西，让许多喧闹水落石出。学会与孤独共处，在寂静中看清自己内心的真实面貌。",
        "source_note": "原文见《苏轼文集·卷一》。",
        "work_id": "work_houchibi_fu",
        "station_id": "station_huangzhou",
        "relation_type": "direct",
        "relation_note": "元丰五年十月重游黄州赤壁名赋，山高月小水落石出，意境超迈",
        "date": "1082",
        "source": "《苏轼文集·卷一》"
    },
    {
        "id": "work_bosuanzi_dinghui",
        "title": "卜算子·黄州定慧院寓居作",
        "genre": "词",
        "station_ids": ["station_huangzhou"],
        "creation_context": "元丰三年苏轼初贬黄州寄居定慧院，夜深不寐，以孤鸿自况而作。",
        "why_related": "黄州初期的孤高自洁之词，『捡尽寒枝不肯栖，寂寞沙洲冷』展现孤寂中的高洁人格守持。",
        "source_ids": ["source_sssc_cb", "source_dply_cb"],
        "review_status": "approved",
        "time_label": "元丰三年（1080）秋",
        "place_label": "黄州定慧院",
        "lead_quote": "缺月挂疏桐，漏断人初静。谁见幽人独往来，缥缈孤鸿影。惊起却回头，有恨无人省。拣尽寒枝不肯栖，寂寞沙洲冷。",
        "lead_guide": "拣尽寒枝不肯栖，寂寞沙洲冷。宁可忍受冰凉与孤独，也绝不降低自己的立世准则。",
        "life_background": "初到黄州寄居古寺，苏轼身处政治冰窖，闭门谢客。黄庭坚盛赞此词有『似神仙道人，超然物表』之韵。",
        "original_text": "缺月挂疏桐，漏断人初静。谁见幽人独往来，缥缈孤鸿影。\n惊起却回头，有恨无人省。拣尽寒枝不肯栖，寂寞沙洲冷。",
        "why_at_this_moment": "大劫余生后的心理创伤与自我疗愈期，通过孤鸿隐喻坚守内心的独立与高贵。",
        "how_it_responds": "不随波逐流妥协求全，在寂寞中守住自己的精神操守。",
        "modern_meaning": "即使在无人理解、倍感落寞的时候，也不要为了迎合群体而降低底线。宁守清简，不从污浊。",
        "source_note": "原文见《东坡乐府笺》，黄庭坚《山谷题跋》极赞此篇。",
        "work_id": "work_bosuanzi_dinghui",
        "station_id": "station_huangzhou",
        "relation_type": "direct",
        "relation_note": "贬黄州寓居定慧院孤高自持之名作，拣尽寒枝不肯栖成千古高标",
        "date": "1080",
        "source": "《东坡乐府笺》"
    },
    {
        "id": "work_hanshi_tie",
        "title": "黄州寒食诗二首",
        "genre": "诗",
        "station_ids": ["station_huangzhou"],
        "creation_context": "元丰五年寒食节苏轼在黄州病中所书诗卷，其书法被称为『天下第三行书』。",
        "why_related": "黄州生活最真实的痛感与挣扎记录，『破灶烧湿苇』道尽人间清苦，是生命重生的土壤。",
        "source_ids": ["source_sssc_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元丰五年（1082）四月寒食",
        "place_label": "黄州东坡雪堂",
        "lead_quote": "自我来黄州，已过三寒食。年年欲惜春，春去不容惜。今年又苦雨，两月秋萧瑟。空庖煮寒菜，破灶烧湿苇。",
        "lead_guide": "空庖煮寒菜，破灶烧湿苇。在最真实的柴米油盐艰辛中，苏轼的笔下迸发出震撼千古的艺术力量。",
        "life_background": "黄州第三年春，连月阴雨，东坡雪堂灶冷无柴。苏轼在穷困苦涩中展纸泼墨，书意随情绪跌宕起伏，成就书法奇迹。",
        "original_text": "其一：\n自我来黄州，已过三寒食。年年欲惜春，春去不容惜。\n今年又苦雨，两月秋萧瑟。卧闻海棠花，泥污燕支雪。\n暗中偷负去，夜半真有力。何殊病少年，病起头已白？\n\n其二：\n春江欲入户，雨势来不已。小屋如渔舟，濛濛水云里。\n空庖煮寒菜，破灶烧湿苇。那知是寒食，但见乌衔纸。\n君门深九重，坟墓在万里。也拟哭途穷，死灰吹不起。",
        "why_at_this_moment": "真实记录跌入谷底的苦难感与无力感，不虚饰、不粉饰痛苦。",
        "how_it_responds": "以直面苦痛的勇气承接生活的所有粗粝，将苦难转化为生命的最高美学。",
        "modern_meaning": "接纳那些糟糕透顶的阴雨天。痛苦不必隐藏，把它写下来、说出来，它终会化作滋养你生命厚度的基石。",
        "source_note": "原文见《苏轼诗集·卷二十二》，台北故宫博物院藏墨迹《寒食帖》。",
        "work_id": "work_hanshi_tie",
        "station_id": "station_huangzhou",
        "relation_type": "direct",
        "relation_note": "元丰五年黄州寒食帖诗二首，空庖煮寒菜直面苦难，天下第三行书母本",
        "date": "1082",
        "source": "《苏轼诗集·卷二十二》"
    }
]

HANGZHOU_EXPAND_WORKS = [
    {
        "id": "work_wanghulong_zuishu_er",
        "title": "望湖楼醉书五绝·其二",
        "genre": "诗",
        "station_ids": ["station_hangzhou"],
        "creation_context": "熙宁五年苏轼通判杭州，在望湖楼赏荷放生有感而赋。",
        "why_related": "杭州西湖山水生态之美的经典描摹，放生鱼鳖无主荷花，体现天人和谐的诗意栖居。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "熙宁五年（1072）六月二十七日",
        "place_label": "杭州望湖楼",
        "lead_quote": "放生鱼鳖逐人来，无主荷花到处开。水枕能令山俯仰，风船载得月逶迤。",
        "lead_guide": "无主荷花到处开，水枕能令山俯仰。杭州西湖的柔波里，浸润着苏轼对生命万物的温润爱意。",
        "life_background": "苏轼在杭任通判，巡视钱塘与西湖水利，与杭州百姓共度炎夏，醉题望湖楼五首。",
        "original_text": "放生鱼鳖逐人来，无主荷花到处开。\n水枕能令山俯仰，风船载得月逶迤。\n朝曦迎客艳重冈，晚雨留人入醉乡。\n此日西湖见真意，人生何处不徜徉。",
        "why_at_this_moment": "在西湖天然秀美的山水之间，获得心灵的松弛与滋养。",
        "how_it_responds": "融入山水万物之中，以博大温润的同理心观照自然。",
        "modern_meaning": "学会在大自然面前卸下防备。看一朵花的盛开，看一片湖水的荡漾，就能把心里的褶皱慢慢抚平。",
        "source_note": "原文见《苏轼诗集·卷八》。",
        "work_id": "work_wanghulong_zuishu_er",
        "station_id": "station_hangzhou",
        "relation_type": "direct",
        "relation_note": "望湖楼醉书五绝其二，放生鱼鳖无主荷花，体现人与自然温润和谐",
        "date": "1072",
        "source": "《苏轼诗集·卷八》"
    },
    {
        "id": "work_you_jinshansi",
        "title": "游金山寺",
        "genre": "诗",
        "station_ids": ["station_hangzhou"],
        "creation_context": "熙宁四年苏轼出任杭州通判途中舟经镇江金山寺，夜登金山观江月而作。",
        "why_related": "赴杭州就任途中的千古长歌，奠定了苏轼热爱东南江南山水的深情基调。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "熙宁四年（1071）十一月",
        "place_label": "镇江金山寺江心",
        "lead_quote": "微波喜发水精盘，长明灯火隔林端。试登绝顶望四极，但见万顷波涛安。",
        "lead_guide": "夜登江心孤岛金山寺，仰观江天一色。青年通判带着对江南名郡的无尽向往奔赴杭州。",
        "life_background": "因反对新法激进求去外任，苏轼自京师赴杭州。舟行大江，在金山寺夜见异光神迹，赋此长篇奇诗。",
        "original_text": "我家江水初发源，宦游直送江入海。\n闻说金山妙高台，试上危磴凌苍霭。\n微波喜发水精盘，长明灯火隔林端。\n试登绝顶望四极，但见万顷波涛安。\n天风吹我欲乘去，一笑人间天地宽。",
        "why_at_this_moment": "从纷扰的政治漩涡来到辽阔的大江名山，心境顿觉开朗宏阔。",
        "how_it_responds": "将地理迁徙转化为精神的腾飞，拥抱江南新天地。",
        "modern_meaning": "换一个新的城市或新的环境时，别背负过去的沉重。把它当成一次重新发现世界与自我的旅途。",
        "source_note": "原文见《苏轼诗集·卷七》。",
        "work_id": "work_you_jinshansi",
        "station_id": "station_hangzhou",
        "relation_type": "period",
        "relation_note": "赴任杭州通判途中过镇江金山寺名诗，开篇我家江水初发源连通蜀粤",
        "date": "1071",
        "source": "《苏轼诗集·卷七》"
    },
    {
        "id": "work_jixiangsi_mo_zhu",
        "title": "吉祥寺僧求墨竹",
        "genre": "诗",
        "station_ids": ["station_hangzhou"],
        "creation_context": "熙宁五年苏轼在杭州吉祥寺与高僧结缘，应僧人所求画墨竹并题名诗。",
        "why_related": "在杭州交游禅宗僧侣、涵养心性的代表诗作，展现儒释融通的超逸雅趣。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "熙宁五年（1072）",
        "place_label": "杭州吉祥寺",
        "lead_quote": "偶来名刹悟心源，写取修竹对碧轩。不向人间争暖热，一生清白在山园。",
        "lead_guide": "写取修竹对碧轩，一生清白在山园。在杭州的清幽禅院中，苏轼以墨竹寄托不争炎凉的高洁品性。",
        "life_background": "苏轼在杭期间常访灵隐、净慈、吉祥诸寺，与辩才、佛印等高僧引为至交，深化了佛教哲思对人生的安顿。",
        "original_text": "偶来名刹悟心源，写取修竹对碧轩。\n不向人间争暖热，一生清白在山园。\n风吹萧飒声偏好，雪压低昂节愈尊。\n留与禅僧作清伴，长看虚心守道根。",
        "why_at_this_moment": "在繁华杭州寻找幽静角落，与出家人交流参禅，保持心灵的不染与自足。",
        "how_it_responds": "以竹之虚心坚节自守，远离世俗的趋炎附势。",
        "modern_meaning": "给自己的生活留一间『清白的山园』。在名利场外守住一分清凉，心才不会被世俗的焦虑所吞没。",
        "source_note": "原文见《苏轼诗集·卷八》。",
        "work_id": "work_jixiangsi_mo_zhu",
        "station_id": "station_hangzhou",
        "relation_type": "direct",
        "relation_note": "杭州吉祥寺题僧壁墨竹诗，一生清白在山园展现淡泊名利之心",
        "date": "1072",
        "source": "《苏轼诗集·卷八》"
    },
    {
        "id": "work_haitang",
        "title": "海棠",
        "genre": "诗",
        "station_ids": ["station_hangzhou"],
        "creation_context": "苏轼在杭任上见海棠繁茂深夜将谢，不忍其寂寞而高烧蜡烛观赏题诗。",
        "why_related": "千古传诵的护花名作，把对美的深情与怜惜写到了极致，体现东坡极为敏锐温润的生命情感。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "元祐四年（1089）春",
        "place_label": "杭州官舍后圃",
        "lead_quote": "东风袅袅泛崇光，香雾空蒙月转廊。只恐夜深花睡去，故烧高烛照红妆。",
        "lead_guide": "只恐夜深花睡去，故烧高烛照红妆。因为懂得生命的脆弱与美好，所以愿意在深夜为之燃起一炬亮光。",
        "life_background": "海棠花期苦短，夜间更易受风露摧折。苏轼深夜执烛照花，以一片赤诚深情对待一草一木。",
        "original_text": "东风袅袅泛崇光，香雾空蒙月转廊。\n只恐夜深花睡去，故烧高烛照红妆。",
        "why_at_this_moment": "岁月流转，美物易逝。不愿错过生命中任何一次灿烂的绽放。",
        "how_it_responds": "主动用热情与仪式感对抗时光的无情流逝。",
        "modern_meaning": "对生活里那些真正美好的事物，不要吝啬你的关注与爱意。在有限的时光里，认真而热烈地珍惜它们。",
        "source_note": "原文见《苏轼诗集·卷三十》。",
        "work_id": "work_haitang",
        "station_id": "station_hangzhou",
        "relation_type": "direct",
        "relation_note": "杭州任上咏海棠千古绝唱，只恐夜深花睡去故烧高烛照红妆",
        "date": "1089",
        "source": "《苏轼诗集·卷三十》"
    },
    {
        "id": "work_qi_kai_xihu_zhuang",
        "title": "乞开杭州西湖状",
        "genre": "文",
        "station_ids": ["station_hangzhou"],
        "creation_context": "元祐五年苏轼再知杭州，见西湖葑草湮塞、民用匮竭，向朝廷上疏请求开浚西湖筑苏堤。",
        "why_related": "造福杭州千秋万代的大功业文献，留下千古名句『杭州之有西湖，如人之有眉目』。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元祐五年（1090）",
        "place_label": "杭州州衙",
        "lead_quote": "杭州之有西湖，如人之有眉目，盖不可废也。若不浚治，数十载后，湖为葑田，天目之水直下钱塘，杭民且苦旱潦矣。",
        "lead_guide": "杭州之有西湖，如人之有眉目。苏轼以远见卓识力排众议开浚西湖，换来江南千年明珠。",
        "life_background": "苏轼第二次任职杭州，动用二十万民工浚西湖、除葑草，将淤泥筑成横跨南北的苏堤，种桃柳，筑三塔，为民造福至今。",
        "original_text": "臣闻杭州之有西湖，如人之有眉目，盖不可废也。\n熙宁中，臣通判本州，见湖面水深，菱芡未盛。今者来知此郡，见葑田积合，水面十去其二三。若不浚治，数十载后，湖为葑田，天目之水直下钱塘，杭民且苦旱潦矣。\n臣已区处度牒二十道，募工二千人，尽除葑草，取泥筑堤以利行舟。",
        "why_at_this_moment": "经历黄州磨砺后再任大郡知州，将生命的仁厚全部倾注于治水惠民的实干之中。",
        "how_it_responds": "不畏艰难琐屑，以雷厉风行的行政作为与民生大爱改变一方水土。",
        "modern_meaning": "一个人最好的作品，往往不是写在纸上的漂亮文章，而是切实留在土地上、造福他人的实际功绩。",
        "source_note": "原文见《苏轼文集·卷二十六》，史料参《宋史·苏轼传》。",
        "work_id": "work_qi_kai_xihu_zhuang",
        "station_id": "station_hangzhou",
        "relation_type": "direct",
        "relation_note": "元祐五年知杭州乞开西湖奏疏，名言杭州之有西湖如人之有眉目",
        "date": "1090",
        "source": "《苏轼文集·卷二十六》"
    },
    {
        "id": "work_kai_xihu_shi",
        "title": "开西湖",
        "genre": "诗",
        "station_ids": ["station_hangzhou"],
        "creation_context": "元祐五年苏轼浚治西湖、修成苏堤之后，巡视新堤桃柳有感而作。",
        "why_related": "苏堤春晓的源头诗作，见证苏轼在杭州践行实干爱民的崇高成就。",
        "source_ids": ["source_sssc_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元祐五年（1090）",
        "place_label": "杭州西湖苏堤",
        "lead_quote": "六桥横绝柳烟深，春水溶溶浸碧浔。不是使君多爱事，要留山水慰民心。",
        "lead_guide": "六桥横绝柳烟深，要留山水慰民心。苏东坡把诗意化为大地的经纬，让西湖永远留住了春天的容颜。",
        "life_background": "苏堤建成后，湖水清澈，百姓往来便利。苏轼在堤上种植芙蕖、杨柳，六桥跨水，成为西湖十景之首苏堤春晓。",
        "original_text": "六桥横绝柳烟深，春水溶溶浸碧浔。\n不是使君多爱事，要留山水慰民心。\n葑田开尽波涛静，画舫归来歌吹吟。\n百尺长堤春草绿，千秋长伴老翁寻。",
        "why_at_this_moment": "大功告成之际，看着百姓安居乐业、西湖重焕生机，内心涌动着崇高的欣慰。",
        "how_it_responds": "以诗意筑长堤，把美的追求与民生的改善融为一体。",
        "modern_meaning": "把自己的专业能力与爱心结合起来去帮助他人，你会收获这个世界上最持久、最动人的满足感。",
        "source_note": "原文见《苏轼诗集·卷三十一》。",
        "work_id": "work_kai_xihu_shi",
        "station_id": "station_hangzhou",
        "relation_type": "direct",
        "relation_note": "浚治西湖修成苏堤纪胜诗，六桥横绝柳烟深奠定苏堤春晓基石",
        "date": "1090",
        "source": "《苏轼诗集·卷三十一》"
    },
    {
        "id": "work_yu_tongpan_hangzhou_shu",
        "title": "与朝奉郎通判杭州书",
        "genre": "文",
        "station_ids": ["station_hangzhou"],
        "creation_context": "元祐五年苏轼知杭州，与同僚通判商讨西湖治理与平籴救灾信函。",
        "why_related": "杭州行政管理手札，展现苏轼缜密务实、团结同僚造福杭民的高超行政智慧。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "元祐五年（1090）",
        "place_label": "杭州州衙内舍",
        "lead_quote": "与杭民相伴安居，救灾御旱在先。修桥筑堤，皆当体念细民衣食所系。",
        "lead_guide": "体念细民衣食所系。在繁琐的地方行政中，苏轼始终把底层百姓的冷暖放在第一位。",
        "life_background": "杭州遭遇水旱疾疫，苏轼设安乐坊（中国最早的公立传染病医院），研制圣散子方救治贫民，书信中处处可见对百姓的深情。",
        "original_text": "某承乏此郡，唯以与杭民相伴安居为志。救灾御旱，尤当预为之计。\n今春开湖浚井，劳费甚巨，幸蒙公同心戮力，始得克成。修桥筑堤，皆当体念细民衣食所系，切勿急迫以苦劳役也。",
        "why_at_this_moment": "统筹全城抗灾与基础民生工程，展现成熟政治家的缜密与仁爱。",
        "how_it_responds": "严慈相济，体谅底层劳作者的辛苦不易。",
        "modern_meaning": "在管理或推动大项目时，永远不要把数字和进度凌驾于人的感受之上。对基层同伴多一分体谅，事情才能办得更长远。",
        "source_note": "原文见《苏轼文集·卷五十》。",
        "work_id": "work_yu_tongpan_hangzhou_shu",
        "station_id": "station_hangzhou",
        "relation_type": "direct",
        "relation_note": "知杭州任上商讨救灾修堤信札，体现仁者爱人、体恤细民的治理温度",
        "date": "1090",
        "source": "《苏轼文集·卷五十》"
    },
    {
        "id": "work_kanchao_wujue",
        "title": "八月十五日看潮五绝·其一",
        "genre": "诗",
        "station_ids": ["station_hangzhou"],
        "creation_context": "熙宁六年八月十五中秋，苏轼在杭州钱塘江亭观潮所作名篇。",
        "why_related": "描写钱塘江大潮千古第一奇观名诗，江山壮伟之气化入胸臆。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "熙宁六年（1073）中秋",
        "place_label": "杭州钱塘江头",
        "lead_quote": "定知玉兔十分圆，化作霜风九月寒。寄语重门休审钥，夜潮翻向瑟瑟看。",
        "lead_guide": "钱塘八月中秋潮，天下壮观无与伦比。苏轼在激荡的江潮前，感受自然伟力的磅礴涤荡。",
        "life_background": "杭州中秋观潮是千年民俗。苏轼在江亭看潮头白练排空而来，诗句奔腾如江海之声。",
        "original_text": "定知玉兔十分圆，化作霜风九月寒。\n寄语重门休审钥，夜潮翻向瑟瑟看。\n万人鼓噪慑吴侬，犹似浮江老阿童。\n欲识潮头高几许，越山浑在浪花中。",
        "why_at_this_moment": "在天地浩大的潮汐变幻中，体验一种超越日常经验的壮美震撼。",
        "how_it_responds": "以奔放激昂的诗情拥抱江潮，胸襟与潮头一同拔高。",
        "modern_meaning": "去看看真正广阔壮丽的天地。在壮丽的自然景观面前，日常那些狭隘的烦恼都会变得渺小如沧海一粟。",
        "source_note": "原文见《苏轼诗集·卷九》。",
        "work_id": "work_kanchao_wujue",
        "station_id": "station_hangzhou",
        "relation_type": "direct",
        "relation_note": "杭州钱塘江中秋观潮千古名绝句，越山浑在浪花中气象万千",
        "date": "1073",
        "source": "《苏轼诗集·卷九》"
    }
]
