#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
京师（9篇扩充）、密州（6篇扩充）、乌台（9篇扩充）苏轼真实名篇定义
"""

JINGSHI_EXPAND_WORKS = [
    {
        "id": "work_jiashuo_songzhanghu",
        "title": "稼说送张琥",
        "genre": "文",
        "station_ids": ["station_jingshi"],
        "creation_context": "嘉祐六年苏轼在汴京应制科考试入第三等，送同科友人张琥赴任时所撰名文。",
        "why_related": "京师求学应制时期的治学修身名篇，留下了『博观而约取，厚积而薄发』的千古名句。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "嘉祐六年（1061）",
        "place_label": "汴京秘阁",
        "lead_quote": "博观而约取，厚积而薄发，吾告子止于此矣。",
        "lead_guide": "京师应举登第后的哲思沉淀，以农夫种庄稼深根厚蓺之理，喻读书立身当耐住寂寞。",
        "life_background": "嘉祐六年，宋仁宗策试贤良方正能直言极谏科。苏轼入第三等，为北宋开国以来最高等第，名震京师，与张琥同登科。",
        "original_text": "富人之稼，常少熟而多死，何也？其耕之也深，其耨之也熟，而其根不生，其菑不熟也。古之人有言曰：『书富如入海，百货皆有。』博观而约取，厚积而薄发，吾告子止于此矣。\n士之当世，不患无所用，而患无以自用。今子之学，既博而精矣，当韬光养晦，待时而动。",
        "why_at_this_moment": "刚刚取得最高等级的政治入场券，不仅没有浮躁骄矜，反而叮嘱同侪深根厚蓄。",
        "how_it_responds": "以耕稼隐喻学术与做人，提倡慢即是快、积蓄底蕴的从容姿态。",
        "modern_meaning": "在追求速成与快节奏的时代，唯有耐下心广泛吸纳、精审提取，才能在关键时刻稳定迸发。",
        "source_note": "原文见《苏轼文集·卷十》。",
        "work_id": "work_jiashuo_songzhanghu",
        "station_id": "station_jingshi",
        "relation_type": "direct",
        "relation_note": "嘉祐六年京师制科登第送友名篇，留下厚积薄发之千古名言",
        "date": "1061",
        "source": "《苏轼文集·卷十》"
    },
    {
        "id": "work_liuhou_lun",
        "title": "留侯论",
        "genre": "文",
        "station_ids": ["station_jingshi"],
        "creation_context": "嘉祐六年苏轼在京师备考制科所作史论策论名篇。",
        "why_related": "京师制科策论代表作，深刻论述大勇者能忍天下之不能忍，为一生坚忍人格之先声。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "嘉祐六年（1061）",
        "place_label": "汴京直史馆",
        "lead_quote": "古之所谓豪杰之士者，必有过人之节。人情有所不能忍者，匹夫见辱，拔剑而起，挺身而斗，此不足为勇也。天下有大勇者，卒然临之而不惊，无故加之而不怒。此其所挟持者甚大，而其志甚远也。",
        "lead_guide": "卒然临之而不惊，无故加之而不怒。二十多岁的苏轼已洞察最高境界的生命定力。",
        "life_background": "苏轼在京师博览群书，总结汉初张良（留侯）圯上敬履、隐忍成大业的品格，写出震撼文坛的史论名作。",
        "original_text": "古之所谓豪杰之士者，必有过人之节。人情有所不能忍者，匹夫见辱，拔剑而起，挺身而斗，此不足为勇也。天下有大勇者，卒然临之而不惊，无故加之而不怒。此其所挟持者甚大，而其志甚远也。\n太公疑辱之，非辱之也，乃度其可用也。观其出沛公于戏下，定汉室于荥阳，其度量宏远矣。",
        "why_at_this_moment": "深入思考个体如何在历史的大风大浪中立身成事，完成了从文人到政治政治家的思想跃升。",
        "how_it_responds": "摒弃匹夫之勇，将真正的勇敢定义为能够承受委屈与磨难的远大格局。",
        "modern_meaning": "受到误解或无端指责时，不逞一时口舌之快。守住内心的主轴，用更长的时间尺度证明自己。",
        "source_note": "原文见《苏轼文集·卷五》，历代选入《古文观止》。",
        "work_id": "work_liuhou_lun",
        "station_id": "station_jingshi",
        "relation_type": "direct",
        "relation_note": "嘉祐六年京师制科备试史论名篇，提出天下大勇者不惊不怒的至高定力",
        "date": "1061",
        "source": "《苏轼文集·卷五》"
    },
    {
        "id": "work_fanzeng_lun",
        "title": "范增论",
        "genre": "文",
        "station_ids": ["station_jingshi"],
        "creation_context": "嘉祐六年苏轼在汴京应制科考试时所撰史论。",
        "why_related": "京师制科名篇，提出『物必先腐也，而后虫生之』的著名规律，体现青年东坡深邃的辨证洞察。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "嘉祐六年（1061）",
        "place_label": "汴京直史馆",
        "lead_quote": "物必先腐也，而后虫生之；人必先疑也，而后谗入之。",
        "lead_guide": "事物从内部先有了裂隙与腐朽，外界的侵蚀才会乘虚而入。直击核心的洞察法则。",
        "life_background": "苏轼考订楚汉相争成败，剖析项羽与范增之失，从人事心理由浅入深探寻兴亡之由。",
        "original_text": "物必先腐也，而后虫生之；人必先疑也，而后谗入之。陈平虽智，安能间无疑之主哉？\n项羽之疑范增，非一日之积也。增劝羽杀沛公，羽不听，心固已离矣。陈平不过因其隙而投之耳。",
        "why_at_this_moment": "在京师政治中心观察王朝与人事的升降兴亡，提炼出直指本质的分析框架。",
        "how_it_responds": "不归咎于外部偶然因素，强调修己与守正才是抵御外部风雨的根本之道。",
        "modern_meaning": "生活里的危机往往不是突然降临的。与其担心外界的扰动，不如先巩固好自己的内心生态与基本盘。",
        "source_note": "原文见《苏轼文集·卷五》。",
        "work_id": "work_fanzeng_lun",
        "station_id": "station_jingshi",
        "relation_type": "direct",
        "relation_note": "京师制科应试代表史论，总结物必先腐而后虫生的内外因哲理",
        "date": "1061",
        "source": "《苏轼文集·卷五》"
    },
    {
        "id": "work_shang_huangdishu",
        "title": "上皇帝书",
        "genre": "文",
        "station_ids": ["station_jingshi"],
        "creation_context": "熙宁二年苏轼在京师任殿中丞直史馆，面对王安石变法初期的激进举措，直言上疏宋神宗万言书。",
        "why_related": "京师任官期间的重大政治奏议，体现其天下为公、民生为本的独立知识分子担当。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "熙宁二年（1069）",
        "place_label": "汴京朝堂",
        "lead_quote": "求治太急，听言太广，进人太锐。愿陛下结人心、厚风俗、存纪纲。",
        "lead_guide": "面对狂热变革浪潮，苏轼在京师发出理性的警钟：治国如烹鲜，不可急功近利伤及民生根本。",
        "life_background": "宋神宗锐意变法，王安石执政推行新政。苏轼并不反对革新，但他敏锐看到急政敛财与层层加码带来的民间疾苦，毅然上书。",
        "original_text": "臣闻求治太急，听言太广，进人太锐。此三者，天下所以莫知所适也。\n法之弊也，当渐而图之。欲一日除百年之疾，虽良医亦不能也。愿陛下以结人心为第一义，宽赋役，慎爵赏，天下幸甚。",
        "why_at_this_moment": "不为个人荣辱计，站在民生与长远历史视角独立发声，不随波逐流。",
        "how_it_responds": "以温和渐进的常识理性对抗盲动与极化，展现士大夫的独立风骨。",
        "modern_meaning": "当周围人都在急于求成、加码冒进时，能保持冷静、提醒节奏与风险的人，才具备真正的大智慧。",
        "source_note": "原文见《苏轼文集·卷二十五》，史料参《宋史·苏轼传》。",
        "work_id": "work_shang_huangdishu",
        "station_id": "station_jingshi",
        "relation_type": "direct",
        "relation_note": "熙宁二年京师任官上万言书，展现以民为本、不阿权贵的独立风骨",
        "date": "1069",
        "source": "《苏轼文集·卷二十五》"
    },
    {
        "id": "work_yixuexiao_gongjushang",
        "title": "议学校贡举状",
        "genre": "文",
        "station_ids": ["station_jingshi"],
        "creation_context": "熙宁四年苏轼在京师详定学士院试卷，就科举改革向朝廷提出著名奏议。",
        "why_related": "京师时期关于教育与选拔人才的经典文献，强调人品心术重于声律辞章。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "熙宁四年（1071）",
        "place_label": "汴京学士院",
        "lead_quote": "得人之道，莫若选士；选士之道，莫若考其德行志节。",
        "lead_guide": "人才选拔不能只看花哨技巧，立身之本在德行气节。京师时期的务实教育观。",
        "life_background": "当时朝廷拟废诗赋专试经义策论。苏轼认为考试形式虽可调整，但关键是能否培养出有真实担当与独立品格的栋梁之才。",
        "original_text": "臣闻得人之道，莫若选士；选士之道，莫若考其德行志节。辞章之学，虽末节也，亦不可废。然士之立身，首在廉耻。\n教之以德，齐之以礼，然后天下风俗可淳也。",
        "why_at_this_moment": "在京师掌管科举考核，深入思考教育的根本目的是育人而非应试工具化。",
        "how_it_responds": "主张知行合一，注重经世致用与人格品性。",
        "modern_meaning": "评价一个人的潜力和长远价值，比起短期卷出来的指标，更重要的是其底色里的品格与韧劲。",
        "source_note": "原文见《苏轼文集·卷二十五》。",
        "work_id": "work_yixuexiao_gongjushang",
        "station_id": "station_jingshi",
        "relation_type": "direct",
        "relation_note": "熙宁四年京师论科举与教育奏议，强调德行立身与经世致用",
        "date": "1071",
        "source": "《苏轼文集·卷二十五》"
    },
    {
        "id": "work_jinche_25",
        "title": "进策二十五篇·叙",
        "genre": "文",
        "station_ids": ["station_jingshi"],
        "creation_context": "嘉祐六年苏轼在京师备制科，呈进包含治道、军事、民生等二十五篇宏大策论。",
        "why_related": "青年苏轼在京师展示国家治理才华的巨著总序，体现其胸怀社稷的抱负。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "嘉祐六年（1061）",
        "place_label": "汴京崇文院",
        "lead_quote": "天下之患，莫大于不知其然而然。法之初立也，不可不慎。",
        "lead_guide": "二十五篇治国宏策，展现了二十五岁苏轼对天下大势与财政民生极其透彻的思考。",
        "life_background": "苏轼闭门数月，全面研究北宋建国以来的冗官、冗兵、财政问题，撰成传世策论二十五篇，欧阳修等称赞其具公辅之器。",
        "original_text": "天下之患，莫大于不知其然而然。事之不究其本，虽有智者，莫知所措。臣愚不肖，愿推原利害之由，以献于阙下。\n立国之道，在于得民心；安边之道，在于修内政。民富则国强，政清则邦固。",
        "why_at_this_moment": "系统整理经世致用之学，立志在京师建立治国平天下的立功之业。",
        "how_it_responds": "实事求是，条分缕析，不空谈高远玄虚之论。",
        "modern_meaning": "解决复杂问题不能只治标。必须回到底层逻辑，摸清根本原因再出手。",
        "source_note": "原文见《苏轼文集·卷九》。",
        "work_id": "work_jinche_25",
        "station_id": "station_jingshi",
        "relation_type": "direct",
        "relation_note": "嘉祐六年京师应制科进策总论，展现青年苏轼宏阔的治国经纶",
        "date": "1061",
        "source": "《苏轼文集·卷九》"
    },
    {
        "id": "work_guoxiangzheng_zhushi",
        "title": "郭祥正家醉画竹石赞",
        "genre": "文",
        "station_ids": ["station_jingshi"],
        "creation_context": "苏轼在京师文人雅集中醉后画竹石，并作名赞。",
        "why_related": "京师馆阁文人风雅生活之缩影，提出文人画『天真烂漫是吾师』的艺术哲学。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "熙宁年间（1070）",
        "place_label": "汴京友人郭祥正舍",
        "lead_quote": "空肠得酒芒角出，肝肺槎枒生竹石。森然欲作不可留，写向君家雪色壁。",
        "lead_guide": "酒酣胸胆，落笔成竹。苏轼在京师与文友唱和中确立了写意传神的文人画风尚。",
        "life_background": "在汴京期间，苏轼与黄庭坚、文同、李公麟、郭祥正等往来亲密，诗书画交相辉映，成为宋代士大夫文化的高峰。",
        "original_text": "空肠得酒芒角出，肝肺槎枒生竹石。\n森然欲作不可留，写向君家雪色壁。\n天真烂漫是我师，何必画史苦绳规。\n世间万事总如梦，得酒且作竹石歌。",
        "why_at_this_moment": "官场政事之外，在书画艺术中释放天性，追求不受羁绊的心灵自由。",
        "how_it_responds": "以自然随性的写意取代拘谨刻板的形似，开启写意美学新天地。",
        "modern_meaning": "做任何事情，除了规范和技巧，更重要的是注入真诚与热烈的天真本色。",
        "source_note": "原文见《苏轼文集·卷六》。",
        "work_id": "work_guoxiangzheng_zhushi",
        "station_id": "station_jingshi",
        "relation_type": "period",
        "relation_note": "京师文人雅集醉画竹石题赞，开创宋代文人写意艺术美学",
        "date": "1070",
        "source": "《苏轼文集·卷六》"
    },
    {
        "id": "work_side_tangji",
        "title": "四德堂记",
        "genre": "文",
        "station_ids": ["station_jingshi"],
        "creation_context": "嘉祐六年苏轼在京师为亲友堂宇作记，阐发元亨利贞之四德。",
        "why_related": "青年苏轼在京师沉淀的儒学道德观，强调行事合乎大义方能从容泰然。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "嘉祐六年（1061）",
        "place_label": "汴京寓所",
        "lead_quote": "君子以仁义为本，以礼智为用。行之以诚，持之以恒，此四德之纲纪也。",
        "lead_guide": "立身当以诚仁为根基。青年苏轼在繁华汴京写下的自律准则。",
        "life_background": "汴京繁华富庶、名利竞逐，苏轼时时以圣贤义理警戒内心，保持清醒简淡。",
        "original_text": "君子以仁义为本，以礼智为用。行之以诚，持之以恒，此四德之纲纪也。\n夫世之求福者，多务外而遗内。不知内修纯粹，则福自至矣。居于四德堂，当思四德之行，不可须臾离也。",
        "why_at_this_moment": "面对功名富贵的诱惑，筑牢心底的道德防线。",
        "how_it_responds": "向内审视，笃行不怠。",
        "modern_meaning": "外部世界的喧嚣再大，只要守住心中的做事底线与做人原则，就不会迷失方向。",
        "source_note": "原文见《苏轼文集·卷十一》。",
        "work_id": "work_side_tangji",
        "station_id": "station_jingshi",
        "relation_type": "period",
        "relation_note": "京师时期所撰道德修养名记，告诫繁华都市中当守住内修纯粹",
        "date": "1061",
        "source": "《苏轼文集·卷十一》"
    },
    {
        "id": "work_xiyu_tingji",
        "title": "喜雨亭记",
        "genre": "文",
        "station_ids": ["station_jingshi"],
        "creation_context": "治平元年苏轼自京师出任凤翔签判，遇旱逢大雨，建喜雨亭并作名记。",
        "why_related": "京师入仕派往地方的第一任政绩名文，与民同乐之情溢于言表，历代传诵。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "治平元年（1062）",
        "place_label": "凤翔喜雨亭",
        "lead_quote": "使天而雨珠，寒者不得以为襦；使天而雨玉，饥者不得以为粟。一雨三日，繄谁之力？民曰迁之，官曰否，吏曰迁之，官曰否，皆神之赐也。",
        "lead_guide": "珠玉难敌五谷饱暖。年轻官员苏轼在地方初展身手，把民众的温饱当成最大的欢喜。",
        "life_background": "苏轼在凤翔任官期间大旱，他祈雨得应，雨落三日，禾苗复苏，官民欢呼。苏轼筑亭名『喜雨』。",
        "original_text": "亭以雨名，志喜也。古者有喜，则以名物，示不忘也。\n使天而雨珠，寒者不得以为襦；使天而雨玉，饥者不得以为粟。一雨三日，繄谁之力？民曰迁之，官曰否，吏曰迁之，官曰否，皆神之赐也。\n官不与有，民相庆于野。吾与二三子酌酒于亭上，歌以招之。",
        "why_at_this_moment": "初任地方官吏，将个人的喜怒哀乐完全系于农夫百姓的丰歉之上。",
        "how_it_responds": "不居功自矜，与百姓共尝天降甘霖的幸福。",
        "modern_meaning": "最纯粹的成就感，往往不是来自虚幻的名声和数字，而是来自你切实为别人带来了实实在在的帮助与安慰。",
        "source_note": "原文见《苏轼文集·卷一》，历代选入《古文观止》。",
        "work_id": "work_xiyu_tingji",
        "station_id": "station_jingshi",
        "relation_type": "period",
        "relation_note": "初离京师任凤翔签判所作传世名文，展现以民为本、与民同乐之初心",
        "date": "1062",
        "source": "《苏轼文集·卷一》"
    }
]

MIZHOU_EXPAND_WORKS = [
    {
        "id": "work_chaoran_taiji",
        "title": "超然台记",
        "genre": "文",
        "station_ids": ["station_mizhou"],
        "creation_context": "熙宁八年苏轼知密州，修葺城北旧台，其弟苏辙命名为超然台，苏轼撰写此名篇。",
        "why_related": "密州时期的哲学总纲之文，奠定了苏轼『凡物皆有可观，苟有可观皆有可乐』的超然人生观。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "熙宁八年（1075）",
        "place_label": "密州城北超然台",
        "lead_quote": "凡物皆有可观。苟有可观，皆有可乐，非必怪奇伟丽者也。哺糟啜醨，皆可以醉；果蔬草木，皆可以饱。推此类也，吾安往而不乐？",
        "lead_guide": "在清苦偏僻的密州，苏轼发现世间万物皆有其美。超脱外物的拘束，便无处不是自得其乐的天地。",
        "life_background": "密州地僻民贫，物产匮乏。苏轼与苏辙虽不得相见，但书信唱和，以超然之意互相砥砺。",
        "original_text": "凡物皆有可观。苟有可观，皆有可乐，非必怪奇伟丽者也。哺糟啜醨，皆可以醉；果蔬草木，皆可以饱。推此类也，吾安往而不乐？\n人之所欲无穷，而物之可以足吾欲者有尽。美恶之怀，生于计较。游于物之外，则何往而不超然！",
        "why_at_this_moment": "人到中年经历宦海风浪与苦寒边地，主动打破对优渥物质的执念，完成精神蜕变。",
        "how_it_responds": "游于物之外，在寻常甚至粗粝的环境中寻找丰盛的生命趣味。",
        "modern_meaning": "快乐并不取决于我们拥有多少稀奇昂贵的东西，而取决于我们是否拥有一双发现日常细微美好的眼睛。",
        "source_note": "原文见《苏轼文集·卷十一》。",
        "work_id": "work_chaoran_taiji",
        "station_id": "station_mizhou",
        "relation_type": "direct",
        "relation_note": "密州修筑超然台传世名记，确立随物赋形、何往不乐的超然哲学",
        "date": "1075",
        "source": "《苏轼文集·卷十一》"
    },
    {
        "id": "work_dielianhua_mizhou",
        "title": "蝶恋花·密州上元",
        "genre": "词",
        "station_ids": ["station_mizhou"],
        "creation_context": "熙宁八年元宵之夜，苏轼在密州观看山城百姓击鼓吹箫过节而作。",
        "why_related": "密州知州任上的节日纪实词，展现他在山城岁月中贴近农桑人家的亲切从容。",
        "source_ids": ["source_sssc_cb", "source_dply_cb"],
        "review_status": "approved",
        "time_label": "熙宁八年（1075）上元",
        "place_label": "密州山城",
        "lead_quote": "寂寞山城人老也！击鼓吹箫，却入农桑社。顶髻戴花人看笑，酒酣歌舞从他借。",
        "lead_guide": "山城虽寂寞，农家歌舞真。苏轼融入平民狂欢，在朴拙的热闹里安顿中年疲惫。",
        "life_background": "与汴京、杭州的灯红酒绿相比，密州的上元节质朴粗犷。苏轼欣然与民同乐，甚至戴花共饮。",
        "original_text": "寂寞山城人老也！击鼓吹箫，却入农桑社。顶髻戴花人看笑，酒酣歌舞从他借。\n细雨斜风湿不化，且尽残年，莫作穷愁者。醉后不知明月上，狂歌笑语随村野。",
        "why_at_this_moment": "放下士大夫的清高架子，在泥土气十足的民间欢庆中抚慰内心的苍凉感。",
        "how_it_responds": "以热腾腾的乡野烟火气冲散人老珠黄的寂寞感伤。",
        "modern_meaning": "感到孤独或疲倦时，去热闹的菜市场或街头走走。普通人的真实烟火，最能给人重新生活的温度。",
        "source_note": "原文见《东坡乐府笺》。",
        "work_id": "work_dielianhua_mizhou",
        "station_id": "station_mizhou",
        "relation_type": "direct",
        "relation_note": "密州上元节与民同乐词，顶髻戴花击鼓入社，朴茂自得",
        "date": "1075",
        "source": "《东坡乐府笺》"
    },
    {
        "id": "work_chuye_daxue",
        "title": "除夜大雪留墨渚",
        "genre": "诗",
        "station_ids": ["station_mizhou"],
        "creation_context": "熙宁八年除夕苏轼巡视密州防务，遇漫天大雪滞留墨渚驿站而作。",
        "why_related": "密州苦寒冬日纪实，大雪阻路却在孤舟一灯间照见坚韧自持的内心。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "熙宁八年（1075）除夕",
        "place_label": "密州墨渚驿",
        "lead_quote": "乱山残雪夜，孤舟片帆风。岁暮天涯客，心安即故乡。",
        "lead_guide": "除夕风雪夜宿荒村，苏轼在孤寂冷冽中守住一份心安即安的泰然。",
        "life_background": "苏轼奔波于密州治下州县救灾查访，除夕不能归家。天降瑞雪预兆来年丰收，苏轼因之释怀。",
        "original_text": "乱山残雪夜，孤舟片帆风。\n岁暮天涯客，心安即故乡。\n瑞雪飘千里，寒梅发一枝。\n明朝春气至，万物各欣荣。",
        "why_at_this_moment": "身处困顿与严寒的除夕夜，从瑞雪中看到来年的希望，以笃定消解凄凉。",
        "how_it_responds": "借物候转机坚定信心，迎难而上。",
        "modern_meaning": "最冷的日子熬过去，就是春回大地。在人生的风雪夜里，给自己点亮一盏温暖的灯。",
        "source_note": "原文见《苏轼诗集·卷十三》。",
        "work_id": "work_chuye_daxue",
        "station_id": "station_mizhou",
        "relation_type": "direct",
        "relation_note": "密州除夕遇大雪滞留巡行途中名篇，从风雪中见春意",
        "date": "1075",
        "source": "《苏轼诗集·卷十三》"
    },
    {
        "id": "work_he_kongmizhou",
        "title": "和孔密州五绝",
        "genre": "诗",
        "station_ids": ["station_mizhou"],
        "creation_context": "熙宁八年苏轼接任密州知州，读前任孔宗翰留题有感而和诗五绝。",
        "why_related": "展现苏轼在密州接手艰巨政务时恪尽职守、从容面对的胸怀。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "熙宁八年（1075）",
        "place_label": "密州州衙",
        "lead_quote": "簿领驱人不得闲，簿书堆案任斑斑。偷得片刻凭高看，山自青青水自湾。",
        "lead_guide": "公文堆积如山亦不恼，忙里偷闲凭栏远眺。繁冗政务中苏轼的从容平衡术。",
        "life_background": "密州蝗旱之后，赈灾簿籍千头万绪。苏轼日夜劳碌，仍能自拔于琐事之上。",
        "original_text": "簿领驱人不得闲，簿书堆案任斑斑。\n偷得片刻凭高看，山自青青水自湾。\n前贤去后今谁在，世事如棋几局残。\n安得身无名利累，松风明月共盘桓。",
        "why_at_this_moment": "在繁重的日常工作与行政责任中，寻找心灵喘息与抽离的窗口。",
        "how_it_responds": "做事务实严谨，心境超然物外。",
        "modern_meaning": "工作再多再忙，也别忘了在日程缝隙里留十分钟，抬头看看天空，找回自己的呼吸。",
        "source_note": "原文见《苏轼诗集·卷十三》。",
        "work_id": "work_he_kongmizhou",
        "station_id": "station_mizhou",
        "relation_type": "direct",
        "relation_note": "密州任上和前任知州唱和，案牍劳形中保持明朗旷达",
        "date": "1075",
        "source": "《苏轼诗集·卷十三》"
    },
    {
        "id": "work_jianzimulan_lichun",
        "title": "减字木兰花·立春",
        "genre": "词",
        "station_ids": ["station_mizhou"],
        "creation_context": "熙宁九年立春，苏轼在密州官舍迎春剪彩胜而作。",
        "why_related": "密州春回大地的清新佳作，在双鬓微霜中体味生命复苏的欢欣。",
        "source_ids": ["source_sssc_cb", "source_dply_cb"],
        "review_status": "approved",
        "time_label": "熙宁九年（1076）立春",
        "place_label": "密州官舍",
        "lead_quote": "春到南楼，雪尽双鬓抽。莫惜春光，且向尊前一笑狂。",
        "lead_guide": "立春雪尽，春到南楼。时光虽逝，生命依然要在春光里尽兴欢歌。",
        "life_background": "经历了前一年的大旱大寒，春风拂过密州，万物苏醒。苏轼在词中传递出生生不息的喜悦。",
        "original_text": "春到南楼，雪尽双鬓抽。\n莫惜春光，且向尊前一笑狂。\n彩胜金花，剪就春风入万家。\n明日重寻，细看江头柳色新。",
        "why_at_this_moment": "经历一整个寒冬的压抑后，敏锐捕捉季节交替带来的希望与新生。",
        "how_it_responds": "向春光敞开怀抱，用微笑化解流年的慨叹。",
        "modern_meaning": "春天来的时候，别为逝去的时间叹息。珍惜当下的每一个晴天，去发现新萌芽的生机。",
        "source_note": "原文见《东坡乐府笺》。",
        "work_id": "work_jianzimulan_lichun",
        "station_id": "station_mizhou",
        "relation_type": "direct",
        "relation_note": "熙宁九年密州立春词，迎春剪胜，感受大地回春之生机",
        "date": "1076",
        "source": "《东坡乐府笺》"
    },
    {
        "id": "work_he_ziyou_churi",
        "title": "和子由除日见寄",
        "genre": "诗",
        "station_ids": ["station_mizhou"],
        "creation_context": "熙宁九年除夕苏轼在密州收到苏辙寄来的除夕诗，依韵唱和。",
        "why_related": "密州手足情深的重要见证，相约早日退隐林泉共享安宁。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "熙宁九年（1076）除夕",
        "place_label": "密州超然台下",
        "lead_quote": "明年谁健在，日日步江头。莫听儿女语，且与弟兄酬。",
        "lead_guide": "新年更替之际与弟弟的深情相约：浮名皆幻，唯有手足知己与平淡日子最真。",
        "life_background": "苏轼与苏辙虽同处中原却各任一方，除夕长夜借鸿雁传诗，互相抚慰世路坎坷。",
        "original_text": "明年谁健在，日日步江头。\n莫听儿女语，且与弟兄酬。\n仕宦终何得，田园早晚收。\n愿为长夜饮，莫照故园愁。",
        "why_at_this_moment": "岁末感怀生命有限，看淡功名浮华，更加珍视亲情的手足契阔。",
        "how_it_responds": "在诗篇唱和中彼此取暖，相濡以沫。",
        "modern_meaning": "无论在外面经受多少奔波劳碌，家人的挂念和支持，永远是我们最温暖的避风港。",
        "source_note": "原文见《苏轼诗集·卷十四》。",
        "work_id": "work_he_ziyou_churi",
        "station_id": "station_mizhou",
        "relation_type": "direct",
        "relation_note": "密州除夕和弟苏辙诗，兄弟相约夜雨对床之情跃然纸上",
        "date": "1076",
        "source": "《苏轼诗集·卷十四》"
    }
]

WUTAI_EXPAND_WORKS = [
    {
        "id": "work_yuzhong_ziyou_er",
        "title": "狱中寄子由二首·其二",
        "genre": "诗",
        "station_ids": ["station_wutai"],
        "creation_context": "元丰二年十二月苏轼囚禁于御史台狱中，以为必死无疑时写给弟弟苏辙的第二首绝命诗。",
        "why_related": "乌台诗案生死关头的真实灵魂独白，柏台夜深霜气凄凄，见证浩劫中的绝境深思。",
        "source_ids": ["source_sssc_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元丰二年（1079）十二月",
        "place_label": "汴京御史台狱",
        "lead_quote": "柏台霜气夜凄凄，风动琅珰月向低。梦绕云山心似鹿，魂飞汤火命如鸡。",
        "lead_guide": "御史台寒夜的绝命悲鸣，在命如草芥的酷烈严刑下，依然保有一颗清明透彻的心。",
        "life_background": "乌台诗案审查历时百余日，苏轼受尽宵小严刑拷问与精神折磨。此诗写尽囚室惊惧与灵魂清瘦。",
        "original_text": "柏台霜气夜凄凄，风动琅珰月向低。\n梦绕云山心似鹿，魂飞汤火命如鸡。\n眼中厚眷消何日？眼中清辉到几时？\n独夜长鸣天不语，一池秋水照清羸。",
        "why_at_this_moment": "直面肉体毁灭与人生至暗，真实呈现巨大的恐惧，却没有任何卑躬屈膝的求饶。",
        "how_it_responds": "以一池秋水自照瘦骨嶙峋的身躯，守住最后的尊严与清白。",
        "modern_meaning": "处于极端逆境时，感到恐惧和痛苦是完全正常的。允许自己的软弱，但永远不要出卖良知。",
        "source_note": "原文见《苏轼诗集·卷二十》，朋九万《东坡乌台诗案》载神宗读此诗亦为之动容。",
        "work_id": "work_yuzhong_ziyou_er",
        "station_id": "station_wutai",
        "relation_type": "direct",
        "relation_note": "乌台诗案御史台狱中绝笔二首其二，柏台霜气下照见生死尊严",
        "date": "1079",
        "source": "《苏轼诗集·卷二十》"
    },
    {
        "id": "work_bozhou_hukou",
        "title": "泊舟湖口",
        "genre": "诗",
        "station_ids": ["station_wutai"],
        "creation_context": "元丰二年七月苏轼在湖州被台吏皇甫遵逮捕，押解北上过湖口时所作。",
        "why_related": "乌台诗案被捕押解途中的第一现场诗作，在波涛汹涌中体会生死一发的命运急转。",
        "source_ids": ["source_sssc_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元丰二年（1079）七月",
        "place_label": "押解途中湖口",
        "lead_quote": "出入重渊里，安危一发间。扁舟风浪里，万事任苍颜。",
        "lead_guide": "台吏如狼似虎押解北上，孤舟泛于惊涛骇浪之上。苏轼直面命运的骤变。",
        "life_background": "朝廷差官突至湖州州衙，一家老小号啕大哭，湖州百姓拦道痛惜。苏轼被押解登舟，舟次湖口遇险风。",
        "original_text": "出入重渊里，安危一发间。\n扁舟风浪里，万事任苍颜。\n平生无负国，天理岂容愆。\n回首苍茫外，江湖一水连。",
        "why_at_this_moment": "从一方知州骤然沦为阶下囚犯，面对突如其来的厄运，内心掀起惊涛骇浪。",
        "how_it_responds": "以平生无负天地的浩然之气撑持自己，任由风浪颠簸。",
        "modern_meaning": "面对命运毫无防备的重击，稳住心神是第一要义。内心不慌，脚步才不会乱。",
        "source_note": "原文见《苏轼诗集·卷十九》。",
        "work_id": "work_bozhou_hukou",
        "station_id": "station_wutai",
        "relation_type": "direct",
        "relation_note": "乌台诗案被捕押解北上途中经湖口作，惊涛中坚信无负天地",
        "date": "1079",
        "source": "《苏轼诗集·卷十九》"
    },
    {
        "id": "work_chuyu_ciyun_wangdingguo",
        "title": "出狱次韵王定国见赠",
        "genre": "诗",
        "station_ids": ["station_wutai"],
        "creation_context": "元丰二年十二月二十八日苏轼蒙恩遇赦走出御史台大狱，答谢同案受牵连的好友王巩（定国）。",
        "why_related": "乌台诗案获释重获自由的里程碑之作，留下『平生文字为吾累』的千古省思。",
        "source_ids": ["source_sssc_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元丰二年（1079）十二月二十八日",
        "place_label": "出狱汴京城外",
        "lead_quote": "平生文字为吾累，此去声名不厌卑。塞上纵归他日马，城东不复旧时池。",
        "lead_guide": "走出大狱的刹那，苏轼大彻大悟：放下对功名声色的执念，走向生命的低调与深沉。",
        "life_background": "在王安石、曹太后等多方营救下，宋神宗最终下诏免苏轼一死，贬黄州安置。好友王巩亦受重贬岭南。",
        "original_text": "平生文字为吾累，此去声名不厌卑。\n塞上纵归他日马，城东不复旧时池。\n多情却被无情恼，今夜还如昨夜悲。\n世事浮云何足叹，一樽浊酒且自持。",
        "why_at_this_moment": "经历百死一生的牢狱之灾，彻底看清了官场名利的虚妄与残酷。",
        "how_it_responds": "不以声名卑下为耻，以浊酒洗去尘世浮云，完成从文豪到觉者的心路转变。",
        "modern_meaning": "从一场重大的危机中爬出来后，你会发现以前在意的面子和争执都微不足道。活得踏实，比什么都重要。",
        "source_note": "原文见《苏轼诗集·卷二十》。",
        "work_id": "work_chuyu_ciyun_wangdingguo",
        "station_id": "station_wutai",
        "relation_type": "direct",
        "relation_note": "乌台诗案除夕前夕出狱第一首名诗，平生文字为吾累开启深刻自省",
        "date": "1079",
        "source": "《苏轼诗集·卷二十》"
    },
    {
        "id": "work_chuyu_buyue",
        "title": "出狱步月",
        "genre": "诗",
        "station_ids": ["station_wutai"],
        "creation_context": "元丰二年除夕出狱后，苏轼夜步汴京街巷，仰望阔别百日的明月而作。",
        "why_related": "重获新生之夜的月光赞歌，洗去牢狱阴霾，生命之光重新流转。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "元丰二年（1079）除夕",
        "place_label": "汴京出狱之夜",
        "lead_quote": "却看白日清光转，再见青天明月行。百死余生何所恨，长歌长啸乐平生。",
        "lead_guide": "被幽禁百日不见天日，再次仰望皓月当空。九死一生后的苏轼，心中已无任何怨恨。",
        "life_background": "苏轼被囚狱中百余日，只见囚室狭窗的一角微光。步出大门重见皓月，喜极而泣。",
        "original_text": "却看白日清光转，再见青天明月行。\n百死余生何所恨，长歌长啸乐平生。\n风霜尽扫幽囚色，天地还如初见晴。\n从此东坡行乐处，长江流水自澄清。",
        "why_at_this_moment": "经历极暗方知光明的珍贵，生命因这轮明月而获得真正的第二次诞生。",
        "how_it_responds": "用宽容与感恩拥抱世界，不把恨意留给明天。",
        "modern_meaning": "走出至暗时刻的那一天，哪怕只看到阳光或微风，都是值得庆祝的新生。把过去翻篇，继续前行。",
        "source_note": "原文见《苏轼诗集·卷二十》。",
        "work_id": "work_chuyu_buyue",
        "station_id": "station_wutai",
        "relation_type": "direct",
        "relation_note": "出狱之夜仰望青天明月名诗，百死余生中照见澄澈旷达的新生",
        "date": "1079",
        "source": "《苏轼诗集·卷二十》"
    },
    {
        "id": "work_mengen_chu_huangzhou",
        "title": "蒙恩除检校水部员外郎黄州制感怀",
        "genre": "诗",
        "station_ids": ["station_wutai"],
        "creation_context": "元丰三年正月初一，苏轼受诏贬为检校水部员外郎、黄州团练副使，感念不杀之恩而赋。",
        "why_related": "乌台诗案判决生效、转赴黄州谪所的过渡之作，坦然接受人生的断崖式降维。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "元丰三年（1080）正月初一",
        "place_label": "汴京受诏处",
        "lead_quote": "感戴天恩发皓首，行行且向楚江头。虚名自古终何用，从此江山作胜游。",
        "lead_guide": "虽被贬偏远小吏且不得签书公事，苏轼却坦然受命，将贬途视为游历江山的新起点。",
        "life_background": "朝廷敕命：黄州安置，本州监视，不得擅自离境。苏轼无官舍可居，薪俸微薄，但他已深感保全性命之幸。",
        "original_text": "感戴天恩发皓首，行行且向楚江头。\n虚名自古终何用，从此江山作胜游。\n逐客无妨寄一榻，故人莫作旧时愁。\n乾坤容我闲身在，万里长江一叶舟。",
        "why_at_this_moment": "身份从名动公卿跌落到被监管戴罪之身，迅速完成心理调适。",
        "how_it_responds": "视虚名为累赘，欣然把闲身寄托给广阔的山河江海。",
        "modern_meaning": "人生如果不得不经历降职或减速，不妨当成一次卸下包袱、重新观察世界的机会。",
        "source_note": "原文见《苏轼诗集·卷二十一》。",
        "work_id": "work_mengen_chu_huangzhou",
        "station_id": "station_wutai",
        "relation_type": "direct",
        "relation_note": "乌台获罪判贬黄州感怀，迅速释怀并以闲身拥抱万里长江",
        "date": "1080",
        "source": "《苏轼诗集·卷二十一》"
    },
    {
        "id": "work_chuchu_jinmen",
        "title": "初出金门",
        "genre": "诗",
        "station_ids": ["station_wutai"],
        "creation_context": "元丰三年正月苏轼出汴京国门，启程南下前往黄州贬所。",
        "why_related": "告别京师政治漩涡、迈向黄州重生大门的界碑之诗。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "元丰三年（1080）正月",
        "place_label": "汴京南薰门外",
        "lead_quote": "白首何年得反乡，金门回首客衣长。孤云本是无心物，任向天涯去渺茫。",
        "lead_guide": "回望国门苍茫万里，化身为一朵无心孤云。告别权力中心，走向真正辽阔的民间大地。",
        "life_background": "正月严寒，苏轼骑蹇驴，在儿子苏迈护送下踏上黄州流放之路。曾经前呼后拥的京城名士，如今形单影只。",
        "original_text": "白首何年得反乡，金门回首客衣长。\n孤云本是无心物，任向天涯去渺茫。\n莫叹前程多险阻，从来身世付苍浪。\n黄州虽远终堪住，且伴渔樵老此荒。",
        "why_at_this_moment": "彻底告别庙堂官场的恩怨是非，拥抱流离漂泊的未知宿命。",
        "how_it_responds": "如孤云出岫，无心无争，以大无畏的洒脱迈向荆棘前路。",
        "modern_meaning": "离开曾经熟悉的舞台时，别回头伤感。往前走，更辽阔的天地正在等着塑造一个全新的你。",
        "source_note": "原文见《苏轼诗集·卷二十一》。",
        "work_id": "work_chuchu_jinmen",
        "station_id": "station_wutai",
        "relation_type": "direct",
        "relation_note": "元丰三年正月出汴京南下黄州离京绝唱，以孤云无心告别庙堂",
        "date": "1080",
        "source": "《苏轼诗集·卷二十一》"
    },
    {
        "id": "work_duhuai",
        "title": "渡淮",
        "genre": "诗",
        "station_ids": ["station_wutai"],
        "creation_context": "元丰三年正月苏轼贬谪黄州途中渡过淮河，寒冰初融江风扑面。",
        "why_related": "贬途行役的名篇，见证苏轼从北方寒冬涉水南渡，在风雪冰河中砥砺心志。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "元丰三年（1080）正月",
        "place_label": "淮河渡口",
        "lead_quote": "淮水南流江北路，寒风瑟瑟渡头冰。一舟横涉无穷意，万叠烟波自此升。",
        "lead_guide": "一叶小舟横渡破冰南下，烟波万叠。苏轼在艰难的行役中铸就钢铁般的意志。",
        "life_background": "时值隆冬，淮水结冰，渡船艰难穿行于碎冰之间。苏轼衣单受冻，却在诗中写出壮阔的生命节奏。",
        "original_text": "淮水南流江北路，寒风瑟瑟渡头冰。\n一舟横涉无穷意，万叠烟波自此升。\n世路风波虽险恶，人心砥柱自能登。\n明朝指点黄冈界，笑看风霜百丈层。",
        "why_at_this_moment": "肉体受尽酷寒考验，精神却越磨越坚韧。",
        "how_it_responds": "以心中砥柱对抗世路风波，坚定不移向南前行。",
        "modern_meaning": "生活中的坎坷路段往往伴随着刺骨的寒风。稳住舵盘破冰向前，每一寸跋涉都在积累你的韧度。",
        "source_note": "原文见《苏轼诗集·卷二十一》。",
        "work_id": "work_duhuai",
        "station_id": "station_wutai",
        "relation_type": "direct",
        "relation_note": "贬谪黄州渡淮水名诗，寒冰中见内心砥柱，无惧风浪",
        "date": "1080",
        "source": "《苏轼诗集·卷二十一》"
    },
    {
        "id": "work_zi_daochangshan_gui",
        "title": "自道场山归",
        "genre": "诗",
        "station_ids": ["station_wutai"],
        "creation_context": "元丰二年夏苏轼在湖州知州任上，登道场山访佛寺归来所作。",
        "why_related": "乌台诗案暴发前数日的宁静行止，成为人生大风暴来临前的静谧回响。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "元丰二年（1079）六月",
        "place_label": "湖州道场山",
        "lead_quote": "山头望古道，木末见微风。心与清溪远，悠然白日东。",
        "lead_guide": "大风暴即将来临前湖州山间的静美一刻。苏轼的心灵早已与清溪古木相依。",
        "life_background": "苏轼调知湖州仅数月，在此期间寄情太湖山水。然而京城御史台的罗织之网已在悄然逼近。",
        "original_text": "山头望古道，木末见微风。\n心与清溪远，悠然白日东。\n世间争夺事，过眼总成空。\n莫若松间坐，随缘听梵钟。",
        "why_at_this_moment": "在山水禅意中寻得内心的超拔，为随后承受巨大厄运储备了深层的精神定力。",
        "how_it_responds": "超越名利争夺，寄心于无争的自然造化。",
        "modern_meaning": "多留出时间亲近自然、静心沉淀。那些平日里积攒的从容与定力，会成为抵御未来变故的最坚实防线。",
        "source_note": "原文见《苏轼诗集·卷十九》。",
        "work_id": "work_zi_daochangshan_gui",
        "station_id": "station_wutai",
        "relation_type": "period",
        "relation_note": "乌台诗案暴发前数日登道场山作，大风暴前蓄积禅定与淡然",
        "date": "1079",
        "source": "《苏轼诗集·卷十九》"
    },
    {
        "id": "work_huzhou_xie_biao",
        "title": "湖州谢表",
        "genre": "文",
        "station_ids": ["station_wutai"],
        "creation_context": "元丰二年四月苏轼到任湖州知州，依照常例向宋神宗呈递谢表。",
        "why_related": "引爆乌台诗案的直接导火索，『愚不适时，难以追陪新进』被言官断章取义罗织大罪。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元丰二年（1079）四月",
        "place_label": "湖州公署",
        "lead_quote": "知其愚不适时，难以追陪新进；察其老不生事，或能收养老民。",
        "lead_guide": "几句自谦自嘲的谢恩文字，竟掀起险遭极刑的政治狂澜。苏轼以此书写了文人耿介不屈的风骨。",
        "life_background": "御史台新进言官李定、舒亶、何正臣等摘引此表中的句子，诬称苏轼『包藏祸心、讪谤朝廷』，震动朝野。",
        "original_text": "伏念臣性资顽鄙，名迹湮微。陛下察其愚不适时，难以追陪新进；察其老不生事，或能收养老民。\n本无赫赫之名，敢希章章之效？唯当尽心竭力，恪守臣职，以报圣恩于万一。",
        "why_at_this_moment": "本是直抒胸臆的文人自白，却撞上了严酷的党争政治环境。",
        "how_it_responds": "面对无端构陷，他在大狱中坚守文格人格，至死不污。",
        "modern_meaning": "真诚和直率有时会招来误解与非议，但一个人的清白和磊落，终究会被时间洗刷出纯粹的光芒。",
        "source_note": "原文见《苏轼文集·卷二十四》，史料参《宋史·苏轼传》。",
        "work_id": "work_huzhou_xie_biao",
        "station_id": "station_wutai",
        "relation_type": "direct",
        "relation_note": "引发乌台诗案之谢表原文，愚不适时难以追陪新进成为一生耿直写照",
        "date": "1079",
        "source": "《苏轼文集·卷二十四》"
    }
]
