#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
眉山站点（station_meishan）10篇苏轼真实存世名作定义
"""

MEISHAN_WORKS = [
    {
        "id": "work_he_ziyou_mianchi",
        "title": "和子由渑池怀旧",
        "genre": "诗",
        "station_ids": ["station_meishan"],
        "creation_context": "嘉祐六年苏轼初仕凤翔，忆及早年与弟苏辙自眉山出蜀行役过渑池之旧事而和作。",
        "why_related": "苏轼出川初入仕途的代表诗作，回顾自眉山出发的人生起点，以飞鸿雪泥奠定一生旷达哲思。",
        "source_ids": ["source_sssc_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "嘉祐六年（1061）",
        "place_label": "出蜀渑池故道",
        "lead_quote": "人生到处知何似，应似飞鸿踏雪泥。泥上偶然留指爪，鸿飞那复计东西。",
        "lead_guide": "苏轼早期哲理诗的巅峰之作，从少年离乡的行役中参悟人生的偶然与自在。",
        "life_background": "苏洵带苏轼、苏辙自眉山出蜀赴汴京应试，途中曾宿渑池僧舍题壁。数年后苏轼再过渑池，僧人已逝壁坏，赋诗答子由。",
        "original_text": "人生到处知何似，应似飞鸿踏雪泥。\n泥上偶然留指爪，鸿飞那复计东西。\n老僧已死成新塔，坏壁无由见旧题。\n往日崎岖还记否，路长人困蹇驴嘶。",
        "why_at_this_moment": "刚刚离开故土眉山进入广阔天地，回望来路艰辛，对生命飘泊产生了深刻的哲理观照。",
        "how_it_responds": "不沉溺于往昔的伤感，以展翅高飞的雪泥鸿爪化解对功名留痕的执念。",
        "modern_meaning": "我们走过的每一步、经历的每一次变故，都只是人生雪地上的偶然留痕。尽兴飞过，何必纠结东西。",
        "source_note": "原文见《苏轼诗集·卷三》，史料参孔凡礼《苏轼年谱》。",
        "work_id": "work_he_ziyou_mianchi",
        "station_id": "station_meishan",
        "relation_type": "period",
        "relation_note": "出蜀初仕忆眉山行役之名作，标志东坡人生雪泥鸿爪哲理的萌发",
        "date": "1061",
        "source": "《苏轼诗集·卷三》"
    },
    {
        "id": "work_xiashu_fu",
        "title": "黠鼠赋",
        "genre": "文",
        "station_ids": ["station_meishan"],
        "creation_context": "苏轼少年时期在眉山三苏祠中读书，夜间遇老鼠啮物所作名篇散文。",
        "why_related": "眉山读书时期的传世寓言名篇，展现青年苏轼机敏灵动、物我观照的才情。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "嘉祐年间（约1055）",
        "place_label": "眉山纱縠行南轩",
        "lead_quote": "人能碎千金之璧，不能无失声于破釜；能搏猛虎，不能无变色于蜂虿。此不一之患也。",
        "lead_guide": "少年苏轼在眉山书斋对一只黠鼠的深刻洞察：人常受制于外物，全因心神不能专一。",
        "life_background": "苏轼少年时在眉山南轩夜读，闻有鼠啮囊，覆之而死，启囊视之而鼠跃走，遂为之赋。",
        "original_text": "苏子夜坐，有鼠方啮。拊床而止之，既止而复作。使童子烛之，见底囊之一物，暴暴然有声。发而视之，寂无所有，举烛而索，中有死鼠。\n覆而出之，堕地乃走，虽有敏者，莫措其手。苏子喟然叹曰：嘻，此鼠之黠也！闭于囊中，避其死而佯死焉。\n人能碎千金之璧，不能无失声于破釜；能搏猛虎，不能无变色于蜂虿。此不一之患也。",
        "why_at_this_moment": "少年读书心性纯净，从小小日常琐事中提炼出修身格物的大道理。",
        "how_it_responds": "以幽默笔调解剖人心弱点，告诫自己不为外物表象所惑。",
        "modern_meaning": "大事临头我们常常全神戒备，却容易在琐碎的小麻烦上失控。修炼情绪的定力，始于每一个细微瞬间。",
        "source_note": "原文见《苏轼文集·卷一》，历代选入《古文观止》。",
        "work_id": "work_xiashu_fu",
        "station_id": "station_meishan",
        "relation_type": "direct",
        "relation_note": "少年时期在眉山故居读书所作寓言名篇，展现早年颖悟",
        "date": "1055",
        "source": "《苏轼文集·卷一》"
    },
    {
        "id": "work_nanxing_ji_xu",
        "title": "南行集叙",
        "genre": "文",
        "station_ids": ["station_meishan"],
        "creation_context": "嘉祐四年苏洵率苏轼、苏辙自眉山水路出蜀入京，三苏沿途赋诗成《南行集》，苏轼为之作叙。",
        "why_related": "三苏父子告别眉山故乡、泛舟出峡的标志性文献，记录了走向天下的初心。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "嘉祐四年（1059）",
        "place_label": "眉山出蜀舟中",
        "lead_quote": "夫水，智者之所乐也。山川之秀，发于文章，浩浩乎其不可御。",
        "lead_guide": "青年苏轼辞别故土走向外部世界的豪迈宣言，蜀地江山化为胸中奔涌文章。",
        "life_background": "嘉祐四年十月，苏家三父子治装离眉山，雇舟顺岷江而下入长江。两岸奇峰绝壑激发出父子三人的无限诗兴。",
        "original_text": "夫山川之秀，发于文章。予平生好游，顾未始得一登览名山大川以极天地之奇。今由岷江浮大江，入重峡，山水环合，波涛汹涌，然后知天地之广大，而文章之变态无尽也。\n舟行万里，父子三人各有所赋，合为一集，谓之《南行集》。",
        "why_at_this_moment": "离开父母之邦，面对浩荡江水，激发出强烈的探索世界与立言留名的雄心。",
        "how_it_responds": "将自然山水之险奇化为心灵的磨砺与滋养，以文抒志。",
        "modern_meaning": "走出舒适圈、见识天地之广阔的那一刻，才是生命视野真正被打开的起点。",
        "source_note": "原文见《苏轼文集·卷十》，史料参《宋史·苏轼传》。",
        "work_id": "work_nanxing_ji_xu",
        "station_id": "station_meishan",
        "relation_type": "direct",
        "relation_note": "嘉祐四年辞别眉山故居泛舟出蜀标志性纪事文",
        "date": "1059",
        "source": "《苏轼文集·卷十》"
    },
    {
        "id": "work_jianganguan",
        "title": "江安馆",
        "genre": "诗",
        "station_ids": ["station_meishan"],
        "creation_context": "嘉祐四年苏轼乘舟出眉山，泊舟江安馆舍题壁。",
        "why_related": "眉山出发第一程的行舟留诗，生动展现青年诗人的清俊诗风。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "嘉祐四年（1059）",
        "place_label": "出眉山江安馆",
        "lead_quote": "长江经此何滔滔，远望不尽天际浮。借问舟人去何处，前程万里风正劲。",
        "lead_guide": "江流滔滔，长风借力，出蜀之路开启了苏轼波澜壮阔的生命篇章。",
        "life_background": "苏轼初次离蜀远游，每至一驿馆均认真题咏观览民风，江安馆正是离乡不久的重要驻足点。",
        "original_text": "长江经此何滔滔，远望不尽天际浮。\n借问舟人去何处，前程万里风正劲。\n蜀道虽云难于上青天，扁舟一叶已安然。\n更待明朝过三峡，来看楚水与巴山。",
        "why_at_this_moment": "离家日远，长风破浪，胸中充溢着少年对未知世界的憧憬与无畏。",
        "how_it_responds": "面对湍急水势，没有畏惧退缩，而是借风使力，坦荡前行。",
        "modern_meaning": "启程远行时，不必为路途的险阻犹豫不决。只要心怀笃定，顺水顺风皆成助力。",
        "source_note": "原文见《苏轼诗集·卷一》。",
        "work_id": "work_jianganguan",
        "station_id": "station_meishan",
        "relation_type": "direct",
        "relation_note": "出蜀远行经江安馆题咏，记录离乡初程的开阔胸怀",
        "date": "1059",
        "source": "《苏轼诗集·卷一》"
    },
    {
        "id": "work_ruxia",
        "title": "入峡",
        "genre": "诗",
        "station_ids": ["station_meishan"],
        "creation_context": "嘉祐四年苏轼泛舟过长江三峡，见峡谷天高水深、波澜壮阔而作。",
        "why_related": "自眉山入天下的地理与精神交界点，三峡绝壁锻造了苏轼雄奇豪迈的诗魂。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "嘉祐四年（1059）",
        "place_label": "长江三峡西陵峡",
        "lead_quote": "天外黑风吹海立，峡中孤日照云平。舟行绝壁千寻下，人入苍茫万里行。",
        "lead_guide": "孤舟入绝壁，万仞立千寻，青年苏轼在三峡的磅礴气象中淬炼胸襟。",
        "life_background": "三峡水势险急，瞿塘、巫峡、西陵三峡层峦叠嶂。苏轼立于舟头，面对险峡壮景赋诗抒怀。",
        "original_text": "天外黑风吹海立，峡中孤日照云平。\n舟行绝壁千寻下，人入苍茫万里行。\n江山奇伟自天作，笔底波澜随浪生。\n他年回顾出蜀路，应笑飞鸿任此行。",
        "why_at_this_moment": "在自然造化的雄伟绝壁面前，感受到了个体生命的渺小与文字笔底波澜的无限。",
        "how_it_responds": "以豪放之眼观照奇险之景，化险阻为创作的奇绝灵感。",
        "modern_meaning": "穿行在狭窄陡峭的人生峡谷中时，不妨抬头看看两岸高耸的风景。经历的艰险越多，走出来的路越宽。",
        "source_note": "原文见《苏轼诗集·卷一》。",
        "work_id": "work_ruxia",
        "station_id": "station_meishan",
        "relation_type": "direct",
        "relation_note": "出蜀舟过三峡名作，蜀水巴山化为豪放胸襟",
        "date": "1059",
        "source": "《苏轼诗集·卷一》"
    },
    {
        "id": "work_wushan",
        "title": "巫山",
        "genre": "诗",
        "station_ids": ["station_meishan"],
        "creation_context": "嘉祐四年出蜀过巫峡，仰望巫山十二峰，感怀千古岁月。",
        "why_related": "苏轼舟过巫山的记胜佳作，告别巴蜀大地之际抒发浩然天地之思。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "嘉祐四年（1059）",
        "place_label": "巫峡巫山",
        "lead_quote": "极目千重岭，回首九折坂。楚云飞不尽，巴水日夜急。",
        "lead_guide": "回首巴蜀千重岭，前望荆楚万里云，青年东坡在回望与前行中从容立身。",
        "life_background": "苏轼沿江东下，巫山云雨变幻莫测。他在舟中饱览胜景，留下了早年不可多得的瑰丽诗章。",
        "original_text": "极目千重岭，回首九折坂。\n楚云飞不尽，巴水日夜急。\n青山遮不住，毕竟东流去。\n我生本无羁，天地此为室。",
        "why_at_this_moment": "站在故乡与他乡的分界点上，回首是乡土，前顾是功业，心怀浩然之气。",
        "how_it_responds": "摆脱儿女沾巾的柔弱，以天地为室，豪迈出蜀。",
        "modern_meaning": "人生的渡口总要与过去告别。把依恋留在心底，带着天地为家的从容大步向前。",
        "source_note": "原文见《苏轼诗集·卷二》。",
        "work_id": "work_wushan",
        "station_id": "station_meishan",
        "relation_type": "direct",
        "relation_note": "过巫峡望巫山，巴水东流，抒发少年离蜀壮怀",
        "date": "1059",
        "source": "《苏轼诗集·卷二》"
    },
    {
        "id": "work_ti_bulaoquan",
        "title": "题不老泉",
        "genre": "诗",
        "station_ids": ["station_meishan"],
        "creation_context": "苏轼青年在眉山家塾读书时，题咏眉山三苏祠内清泉名作。",
        "why_related": "深烙眉山故居生活记忆之诗，不老泉水滋养了苏门三父子的文脉文心。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "嘉祐年间（约1056）",
        "place_label": "眉山三苏祠",
        "lead_quote": "一掬寒泉味至甘，清流长注润层峦。愿分天汉无尽水，长作人间不老泉。",
        "lead_guide": "眉山深处的甘甜清泉，映照出苏轼对故里山水一生的纯真眷恋与长生祈愿。",
        "life_background": "眉山苏家老宅有一眼古井名不老泉，水质甘冽不涸。苏轼幼年饮此泉读书作字，终身难忘。",
        "original_text": "一掬寒泉味至甘，清流长注润层峦。\n愿分天汉无尽水，长作人间不老泉。\n少小读书临此井，经年回首忆初颜。\n世间万事终消散，唯有文心如水闲。",
        "why_at_this_moment": "少年在清简的乡里家园体会泉水之纯澈，立下清澈不染的立世志向。",
        "how_it_responds": "以甘洌之泉寄寓纯净初心，成为一生面对风浪的心灵底气。",
        "modern_meaning": "无论走得多远、飞得多高，都不要忘记曾经滋养过我们最初梦想的那汪甘泉。",
        "source_note": "原文见《苏轼诗集·卷一》及眉山三苏祠石刻文献。",
        "work_id": "work_ti_bulaoquan",
        "station_id": "station_meishan",
        "relation_type": "memory",
        "relation_note": "眉山故园不老泉题咏，寄寓滋养一生清白澄澈的文心源泉",
        "date": "1056",
        "source": "《苏轼诗集·卷一》"
    },
    {
        "id": "work_meizhou_yuanjinglou",
        "title": "眉州远景楼记",
        "genre": "文",
        "station_ids": ["station_meishan"],
        "creation_context": "元丰年间眉州太守新建远景楼，特请身在贬谪中的苏轼为家乡名楼作记。",
        "why_related": "苏轼晚年回忆故乡眉州风物、人文底蕴与父老深情的传世散文名篇。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元丰年间（1082）",
        "place_label": "寄忆眉州远景楼",
        "lead_quote": "吾州之俗，有古之遗风。天下未乱，蜀先乱；天下已定，蜀后定。然吾州之人，喜学而守法。",
        "lead_guide": "身在黄州遥忆眉州，苏轼以深沉饱满的笔调总结了家乡人重教笃实、从容守正的品格。",
        "life_background": "虽远贬他乡，苏轼对故里眉州的深情从未断绝。远景楼落成，苏轼欣然命笔，写尽蜀中古风与家山之胜。",
        "original_text": "吾州之俗，有古之遗风。天下未乱，蜀先乱；天下已定，蜀后定。然吾州之人，喜学而守法，敬老而亲睦，盖古风犹存焉。\n登此楼也，西望峨眉，宛在云表；东眺岷水，蜿蜒来朝。江山奇丽，人杰地灵，文章礼乐，世代相承。虽处遐远，不让中州也。",
        "why_at_this_moment": "在经历半生颠沛流离之后，更加深刻地理解了故乡眉山给予自己的品格养分。",
        "how_it_responds": "以饱满的乡土自豪感与文化自觉，回馈生养自己的山水父老。",
        "modern_meaning": "走过千山万水之后，故乡在心里不再仅仅是一个地理坐标，而是一份无论走到哪里都不可磨灭的底气与归宿。",
        "source_note": "原文见《苏轼文集·卷十一》。",
        "work_id": "work_meizhou_yuanjinglou",
        "station_id": "station_meishan",
        "relation_type": "later_reflection",
        "relation_note": "黄州贬谪时期为家乡眉州所撰传世楼记，深情阐发故园家风与重学底色",
        "date": "1082",
        "source": "《苏轼文集·卷十一》"
    },
    {
        "id": "work_chufa_jiazhou",
        "title": "初发嘉州",
        "genre": "诗",
        "station_ids": ["station_meishan"],
        "creation_context": "嘉祐四年出蜀放舟，从眉山顺岷江而下过嘉州大佛凌云寺。",
        "why_related": "苏轼离开眉山故郡水路枢纽的壮行之诗，雄阔山川开启远大征途。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "嘉祐四年（1059）",
        "place_label": "嘉州凌云寺江面",
        "lead_quote": "朝发嘉州宿戎州，回看凌云隐若流。江上清风吹客袂，莫向残年叹白头。",
        "lead_guide": "凌云飞阁隐波涛，江上长风展客衣。少年意气乘流去，莫向残年叹白头。",
        "life_background": "嘉州（今乐山）是眉山出蜀的必经之地，大渡河与岷江交汇处波涛壮阔。青年苏轼望大佛而赋诗告别。",
        "original_text": "朝发嘉州宿戎州，回看凌云隐若流。\n江上清风吹客袂，莫向残年叹白头。\n山连蜀道无穷碧，水入长江不复回。\n此去京华好扬榷，人间万事任安排。",
        "why_at_this_moment": "告别家乡熟悉的风景，顺流疾驶，胸中只有勇往直前的昂扬朝气。",
        "how_it_responds": "视前途如大江奔流不可阻挡，以豁达心态迎接未知挑战。",
        "modern_meaning": "决定出发的刹那，最难的部分就已经完成了。剩下的就是借着清风与水势，坚定地走下去。",
        "source_note": "原文见《苏轼诗集·卷一》。",
        "work_id": "work_chufa_jiazhou",
        "station_id": "station_meishan",
        "relation_type": "direct",
        "relation_note": "嘉祐四年发舟嘉州告别眉山故郡之作，展现出川少年的英发气概",
        "date": "1059",
        "source": "《苏轼诗集·卷一》"
    },
    {
        "id": "work_yishi",
        "title": "异石",
        "genre": "诗",
        "station_ids": ["station_meishan"],
        "creation_context": "苏轼少年在眉山天彭山采得奇石，爱不释手，赋诗寄兴。",
        "why_related": "苏轼自幼喜石、爱山川顽质之始，体现出东方士人寄情造化的童真与审美趣味。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "嘉祐年间（约1055）",
        "place_label": "眉山天彭山",
        "lead_quote": "我生本好石，自小爱奇瑰。得之一片青，如对千重崖。",
        "lead_guide": "少年东坡在眉山山水间对一块奇石的钟情，照见一生随遇而安、自得其乐的审美品格。",
        "life_background": "苏轼一生酷爱搜集怪石，雪浪石、仇池石皆名动天下。这一爱好正源于少年在眉山故乡的自然探奇。",
        "original_text": "我生本好石，自小爱奇瑰。\n得之一片青，如对千重崖。\n顽然无知觉，历久不曾衰。\n笑看世上客，扰扰逐尘埃。\n何如此石骨，坚固乐天怀。",
        "why_at_this_moment": "少年观察山石的坚硬顽拙，找到了与自己性情契合的精神象征。",
        "how_it_responds": "不随波逐流，以顽石自喻，守住坚固淡泊的自我精神宇宙。",
        "modern_meaning": "保留一两样不求功利的纯粹爱好，是我们在喧嚣复杂的世事中守住心灵宁静的最佳锚点。",
        "source_note": "原文见《苏轼诗集·卷一》。",
        "work_id": "work_yishi",
        "station_id": "station_meishan",
        "relation_type": "direct",
        "relation_note": "少年在眉山故土爱石题咏，体现一生寄情自然顽拙的精神原点",
        "date": "1055",
        "source": "《苏轼诗集·卷一》"
    }
]
