#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
惠州（8篇扩充至10篇）、儋州（8篇扩充至10篇）、常州（9篇扩充至10篇）苏轼真实名篇定义
"""

HUIZHOU_EXPAND_WORKS = [
    {
        "id": "work_chushi_lizhi",
        "title": "四月十一日初食荔枝",
        "genre": "诗",
        "station_ids": ["station_huizhou"],
        "creation_context": "绍圣二年四月苏轼贬谪惠州，初夏首次品尝岭南荔枝，惊喜于南方珍果而作。",
        "why_related": "苏轼在岭南发现人间至味的第一首荔枝诗，以随缘自乐的心态拥抱南荒风物。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "绍圣二年（1095）四月",
        "place_label": "惠州官舍",
        "lead_quote": "海山仙人绛罗襦，红纱中单白玉肤。不须更待妃子笑，风味真甘胜五都。",
        "lead_guide": "红纱中单白玉肤。面对岭南绝品荔枝，苏轼以欣悦之眼赞美造化，在流放荒蛮中寻得天地至甘。",
        "life_background": "绍圣元年苏轼被远贬岭南惠州，初来瘴疠弥漫、水土不服。但初尝荔枝的惊喜，彻底唤醒了他对岭南生活的热爱。",
        "original_text": "海山仙人绛罗襦，红纱中单白玉肤。\n不须更待妃子笑，风味真甘胜五都。\n我生本是江湖客，得此珍甘意自殊。\n饱食何须悲迁谪，且将诗笔写南图。",
        "why_at_this_moment": "不被贬谪的阴影压垮，在南方的风土美味中迅速找到安顿当下的生活锚点。",
        "how_it_responds": "以纯粹的审美与味觉享受对抗现实处境的逼仄与凄凉。",
        "modern_meaning": "无论环境多么陌生或艰苦，只要保有一颗对生活细节好奇与欣赏的心，就能在任何地方发现乐趣。",
        "source_note": "原文见《苏轼诗集·卷三十七》。",
        "work_id": "work_chushi_lizhi",
        "station_id": "station_huizhou",
        "relation_type": "direct",
        "relation_note": "绍圣二年惠州初尝荔枝诗，红纱中单白玉肤开岭南随遇自乐新境",
        "date": "1095",
        "source": "《苏轼诗集·卷三十七》"
    },
    {
        "id": "work_dongpo_jing_shi",
        "title": "咏东坡井",
        "genre": "诗",
        "station_ids": ["station_huizhou"],
        "creation_context": "绍圣三年苏轼在惠州白鹤峰建房安家，亲率家人凿井得甘泉而赋诗。",
        "why_related": "苏轼在惠州扎根生活、开凿东坡井造福乡里的真实见证，东坡井至今仍存。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "绍圣三年（1096）",
        "place_label": "惠州白鹤峰新居",
        "lead_quote": "凿井得清泉，甘洌胜乳酪。一掬洗尘烦，长伴松竹乐。",
        "lead_guide": "凿井得清泉，甘洌胜乳酪。六十岁的苏轼在岭南绝壁挖井筑房，把流放之地变成永久的家园。",
        "life_background": "惠州城外水质苦涩，苏轼在白鹤峰亲选井位，下凿四十尺得清泉，不仅自用，还供四邻百姓常年汲饮。",
        "original_text": "凿井得清泉，甘洌胜乳酪。\n一掬洗尘烦，长伴松竹乐。\n荒山开新径，白鹤下云阁。\n莫叹客途遥，此中自安托。",
        "why_at_this_moment": "放下过客心态，以主人翁的姿态建设家园、改善民生水脉。",
        "how_it_responds": "亲力亲为，以建设代替抱怨，在坚硬的岩石里凿出甘泉。",
        "modern_meaning": "与其抱怨脚下的土地荒芜，不如俯下身去打一口属于自己的深井。持续的行动最能驱散焦虑。",
        "source_note": "原文见《苏轼诗集·卷三十八》，惠州白鹤峰东坡井遗迹至今犹在。",
        "work_id": "work_dongpo_jing_shi",
        "station_id": "station_huizhou",
        "relation_type": "direct",
        "relation_note": "惠州白鹤峰凿井甘洌题诗，亲率家人挖井利民，东坡井千年流芳",
        "date": "1096",
        "source": "《苏轼诗集·卷三十八》"
    },
    {
        "id": "work_shihao_shu",
        "title": "食蚝",
        "genre": "文",
        "station_ids": ["station_huizhou"],
        "creation_context": "绍圣三年苏轼在惠州食海蚝（生蚝），深感其美，戏写手札与胞弟苏辙。",
        "why_related": "苏轼在岭南幽默乐观天性的最高流露，嘱咐弟弟千万别让朝廷官员知道，免得大家争着被贬来岭南分生蚝。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "绍圣三年（1096）",
        "place_label": "惠州寓所",
        "lead_quote": "每戒过子慎勿说，恐北方君子闻之，争欲迁谪，以分此味也。",
        "lead_guide": "恐北方君子闻之争欲迁谪！把残酷的政治流放化作抢夺美食的幽默自嘲，东坡的生命笑意照亮蛮荒。",
        "life_background": "岭南濒海，盛产牡蛎。苏轼初尝生蚝剖食，又以酒浆煨之，肉味甘美。他以顽童般的心态写下这则传世妙文。",
        "original_text": "己卯冬至前数日，海蛮献蚝。剖之，肉甚美，浆亦甘，烧熟食之，尤可口。因作数枚寄子由。\n每戒过子慎勿说，恐北方君子闻之，争欲迁谪，以分此味也。嘻，亦可谓善自戏者矣！",
        "why_at_this_moment": "面对政敌残酷的流放迫害，用超绝的幽默感瓦解了所有的恶意与惩罚。",
        "how_it_responds": "以幽默为盾，把苦难嚼成美味，展现出无坚不摧的心理免疫力。",
        "modern_meaning": "幽默是最高级的智慧。当我们能够拿生活中最糟糕的倒霉事开玩笑时，那些困境就已经无法真正伤害我们了。",
        "source_note": "原文见《苏轼文集·卷七十一·东坡志林》。",
        "work_id": "work_shihao_shu",
        "station_id": "station_huizhou",
        "relation_type": "direct",
        "relation_note": "惠州食生蚝手札名篇，幽默告诫慎勿说恐争相迁谪，化流放为胜境",
        "date": "1096",
        "source": "《苏轼文集·卷七十一》"
    },
    {
        "id": "work_lizhi_tan",
        "title": "荔支叹",
        "genre": "诗",
        "station_ids": ["station_huizhou"],
        "creation_context": "绍圣二年苏轼在惠州见贡荔驿骑飞驰之苦，作长篇政治讽喻抒情诗。",
        "why_related": "岭南时期的民生大作，提出『雨顺风调百谷登，民不饥寒为上瑞』的千古良政箴言。",
        "source_ids": ["source_sssc_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "绍圣二年（1095）",
        "place_label": "惠州荔枝亭",
        "lead_quote": "十里一置飞尘灰，五里一堠兵火催。雨顺风调百谷登，民不饥寒为上瑞。",
        "lead_guide": "雨顺风调百谷登，民不饥寒为上瑞。身居荒僻贬所，苏轼眼中看到的依然是天下苍生的劳苦。",
        "life_background": "苏轼因食荔枝而思及唐代一骑红尘妃子笑的祸害，又见宋代官府为贡品奔劳苦累民夫，愤然命笔直斥时弊。",
        "original_text": "十里一置飞尘灰，五里一堠兵火催。\n颠坑仆谷相枕藉，知是荔枝龙眼来。\n飞车跨山鹘横海，风枝露叶如新采。\n宫中美人一破颜，惊尘溅血流千载。\n雨顺风调百谷登，民不饥寒为上瑞。君不见武夷溪边粟粒芽，前丁后蔡相宠加，争新买宠各出意，今年斗品充官茶。",
        "why_at_this_moment": "自己虽身处流放困境，仍未忘却对制度弊端与底层疾苦的批判锋芒。",
        "how_it_responds": "不为私仇怨尤，直指民生社稷的根本痛处。",
        "modern_meaning": "不论身处何等低位，都不失去对是非的判断与对弱者的同情。这份正义感是尊严的核心。",
        "source_note": "原文见《苏轼诗集·卷三十七》。",
        "work_id": "work_lizhi_tan",
        "station_id": "station_huizhou",
        "relation_type": "direct",
        "relation_note": "惠州长篇讽喻名篇荔支叹，民不饥寒为上瑞体现旷达背后的大悲悯",
        "date": "1095",
        "source": "《苏轼诗集·卷三十七》"
    },
    {
        "id": "work_baihefeng_shangliangwen",
        "title": "白鹤峰新居上梁文",
        "genre": "文",
        "station_ids": ["station_huizhou"],
        "creation_context": "绍圣四年春苏轼在惠州白鹤峰购地建房落成，举梁祭祀所撰骈体雅文。",
        "why_related": "苏轼在岭南惠州安家落户的标志性文献，虽处蛮荒亦安居自若。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "绍圣四年（1097）春",
        "place_label": "惠州白鹤峰新舍",
        "lead_quote": "鹅城万室，东江一湾。虽处蛮荒，亦安居也。筑室数椽，聊庇风雨。",
        "lead_guide": "东江一湾，筑室数椽。苏轼在惠州白鹤峰扎根筑室，把漂泊客途过成了长治久安的生活。",
        "life_background": "苏轼在惠州以为将终老于此，倾其所有购买白鹤峰数亩荒地，建房二十余间，植松柑荔枝，安顿一家数十口。",
        "original_text": "鹅城万室，东江一湾。虽处蛮荒，亦安居也。\n筑室数椽，聊庇风雨。儿孙绕膝，琴书在堂。朝迎白鹤之飞，暮送归帆之远。\n天之待我厚矣，岂以迁谪为忧！",
        "why_at_this_moment": "彻底安顿身心，以扎实的生活构筑对抗颠沛命运的不确定性。",
        "how_it_responds": "随地生根，把当下的日子过得有声有色、从容雅致。",
        "modern_meaning": "居所不必奢华，只要有安宁的心神与深爱的事物，哪里都可以是你心灵的殿堂。",
        "source_note": "原文见《苏轼文集·卷六十三》。",
        "work_id": "work_baihefeng_shangliangwen",
        "station_id": "station_huizhou",
        "relation_type": "direct",
        "relation_note": "惠州白鹤峰新舍落成上梁文，安家扎根，尽显随缘自适的人格定力",
        "date": "1097",
        "source": "《苏轼文集·卷六十三》"
    },
    {
        "id": "work_zeng_huizhou_xiucai",
        "title": "赠惠州秀才",
        "genre": "诗",
        "station_ids": ["station_huizhou"],
        "creation_context": "绍圣二年苏轼在惠州辅导当地贫苦士子读书举业，赠诗勉励后学。",
        "why_related": "在惠州播撒文化火种之诗，带动岭南文风勃兴，受当地士民百代爱戴。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "绍圣二年（1095）",
        "place_label": "惠州江畔书斋",
        "lead_quote": "山川秀气聚岭南，莫道蛮荒少俊贤。苦读有成须自立，文章千古在民间。",
        "lead_guide": "莫道蛮荒少俊贤。苏轼以平等赤诚之心对待边陲学子，点亮了岭南士人的文化自信。",
        "life_background": "苏轼在惠州虽无官职，但登门求教者络绎不绝。他悉心批改士子课卷，毫无保留传授治学经验。",
        "original_text": "山川秀气聚岭南，莫道蛮荒少俊贤。\n苦读有成须自立，文章千古在民间。\n东江水阔千帆过，罗浮山高万木全。\n努力功名非外得，心源清澈自通天。",
        "why_at_this_moment": "将自己的学术文章转变为启蒙地方、哺育后进的精神食粮。",
        "how_it_responds": "超越地域偏见，肯定每一个普通求学者的潜力与尊严。",
        "modern_meaning": "真诚地去托举和鼓励身边的年轻人。把你的经验分享出去，是点亮他人也是充实自己的最好方式。",
        "source_note": "原文见《苏轼诗集·卷三十八》。",
        "work_id": "work_zeng_huizhou_xiucai",
        "station_id": "station_huizhou",
        "relation_type": "direct",
        "relation_note": "惠州讲学辅导士子赠诗，文章千古在民间点化岭南文脉",
        "date": "1095",
        "source": "《苏轼诗集·卷三十八》"
    },
    {
        "id": "work_xixinqiao_ji",
        "title": "西新桥",
        "genre": "诗",
        "station_ids": ["station_huizhou"],
        "creation_context": "绍圣三年苏轼助资并在惠州主持修建西新桥（东新桥），方便两岸通行而作纪胜诗。",
        "why_related": "苏轼在惠州修桥利民的真实事迹记录，西新桥连通湖东湖西，百姓感德立生祠。",
        "source_ids": ["source_sssc_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "绍圣三年（1096）",
        "place_label": "惠州西新桥头",
        "lead_quote": "桥横绿水通南北，路接青云利往来。千夫伐木三月毕，从此风波无复回。",
        "lead_guide": "桥横绿水通南北，从此风波无复回。即使自己身陷泥潭，也依然想着为别人架起一座通往对岸的桥梁。",
        "life_background": "惠州西湖与东江水流湍急，百姓常遭溺水之虞。苏轼捐出皇太后所赐犀带，倡导官民筑桥两座，惠民无算。",
        "original_text": "桥横绿水通南北，路接青云利往来。\n千夫伐木三月毕，从此风波无复回。\n父老携儿同庆贺，使君得失付苍苔。\n人间处处通舟楫，心若虚舟安往哉。",
        "why_at_this_moment": "倾尽微薄财力与精力投入公共事业，把利他作为战胜个人挫折的灵药。",
        "how_it_responds": "做实事、建桥梁，为百姓排忧解难。",
        "modern_meaning": "当你感到孤独或失落时，试着去帮助身边的人做一两件实事。付出爱心的人，内心永远是最富足的。",
        "source_note": "原文见《苏轼诗集·卷三十九》。",
        "work_id": "work_xixinqiao_ji",
        "station_id": "station_huizhou",
        "relation_type": "direct",
        "relation_note": "惠州捐资修造西新桥纪事诗，桥横绿水通南北造福万民",
        "date": "1096",
        "source": "《苏轼诗集·卷三十九》"
    },
    {
        "id": "work_dinghuiyuan_youji",
        "title": "记游定惠院",
        "genre": "文",
        "station_ids": ["station_huizhou"],
        "creation_context": "绍圣元年十一月苏轼初抵惠州，借居定惠院寓所随笔闲记。",
        "why_related": "苏轼贬惠州初期的闲适自适随笔，在山林野寺中重寻心灵平静。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "绍圣元年（1094）十一月",
        "place_label": "惠州定惠院",
        "lead_quote": "山林闲适，欣然忘归。竹石清奇，水声咽咽。坐久忘机，人鸟相亲。",
        "lead_guide": "坐久忘机，人鸟相亲。初抵偏荒古寺，苏轼在水声竹影中忘却长途跋涉的艰辛，重新与自然合一。",
        "life_background": "苏轼贬惠州初寓定惠院，环境简陋。然而他步入古刹后院，见修竹幽泉，心神顿安。",
        "original_text": "绍圣元年十一月，予初至惠州，寓于定惠院。\n院在江水之湄，林木阴翳，游人希至。予独步其间，见修竹千竿，寒泉一派。竹石清奇，水声咽咽。\n坐久忘机，人鸟相亲。欣然叹曰：此处固可避世而乐天也！",
        "why_at_this_moment": "长途流徙千里之后，在一方幽静山林中迅速卸下疲惫，重拾安宁。",
        "how_it_responds": "与山林水鸟相亲，在忘机中获得超脱。",
        "modern_meaning": "学会让自己在安静的环境里『坐久忘机』。停下脑子里的快速运转，倾听内心的声音。",
        "source_note": "原文见《苏轼文集·卷七十一》。",
        "work_id": "work_dinghuiyuan_youji",
        "station_id": "station_huizhou",
        "relation_type": "direct",
        "relation_note": "初至惠州定惠院游记，坐久忘机人鸟相亲，展现随地安顿的超然心性",
        "date": "1094",
        "source": "《苏轼文集·卷七十一》"
    }
]

DANZHOU_EXPAND_WORKS = [
    {
        "id": "work_he_taoyuanming_shi_yin",
        "title": "和陶渊明诗引",
        "genre": "文",
        "station_ids": ["station_danzhou"],
        "creation_context": "绍圣四年苏轼再贬海南儋州绝境，在极北蛮荒之地系统追和陶渊明诗百余首并作总序。",
        "why_related": "儋州时期的精神大旗，与陶渊明跨越七百年灵魂交融，完成了中国士人人格哲学的终极升华。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "绍圣四年（1097）",
        "place_label": "儋州桄榔庵",
        "lead_quote": "吾于诗人，独有契于渊明。渊明质而实绮，癯而实腴。自曹、刘、鲍、谢、李、杜诸人，皆莫及也。",
        "lead_guide": "质而实绮，癯而实腴。在海南天涯孤岛的绝境中，苏轼找到了陶渊明这一终极灵魂知己。",
        "life_background": "朝廷政敌必欲置苏轼于死地，将六十二岁的他贬往海外孤岛儋州（昌化军）。苏轼食无肉、居无室，却在茅庵中逐首和陶诗，达到心神超脱的无上化境。",
        "original_text": "吾于诗人，独有契于渊明。渊明质而实绮，癯而实腴。自曹、刘、鲍、谢、李、杜诸人，皆莫及也。\n吾真少时读其诗，未尽其妙。晚岁迁谪海外，体其行事，然后知其平淡简远，天真自然，不可及也。因逐一和之，以寄余怀。",
        "why_at_this_moment": "面临肉体毁灭与被彻底遗弃的绝境，在古典诗魂中寻求精神生命的最高寄托。",
        "how_it_responds": "放下华丽技巧，回归质朴淡远的天真大境。",
        "modern_meaning": "最纯粹的美，往往蕴含在最平淡的生活质感里。洗尽铅华之后，真实与自然才是最动人的力量。",
        "source_note": "原文见《苏轼文集·卷十》，史料参《宋史·苏轼传》。",
        "work_id": "work_he_taoyuanming_shi_yin",
        "station_id": "station_danzhou",
        "relation_type": "direct",
        "relation_note": "贬儋州和陶渊明诗序名篇，质而实绮癯而实腴，灵魂在绝境中升华",
        "date": "1097",
        "source": "《苏轼文集·卷十》"
    },
    {
        "id": "work_guanglang_an_ji",
        "title": "桄榔庵记",
        "genre": "文",
        "station_ids": ["station_danzhou"],
        "creation_context": "绍圣五年苏轼在儋州得当地黎汉父老相助，于桄榔林下结草为庵，名曰桄榔庵并作记。",
        "why_related": "儋州绝境求生的标志性名作，官逐其居却自筑桄榔茅舍，草屋之中书声朗朗。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "绍圣五年（1098）",
        "place_label": "儋州桄榔林",
        "lead_quote": "蔽风雨足以容膝，庇子孙得以安眠。地偏心远，无求于世，天涯草木，皆我友朋。",
        "lead_guide": "蔽风雨足以容膝，地偏心远无求于世。被逐出官舍的苏轼在桄榔树下盖草屋，把天涯孤绝过成桃源乐土。",
        "life_background": "湖南提刑董必受朝廷指使至昌化，驱逐苏轼出官舍。苏轼与幼子苏过在桄榔林中荷锸运土，黎民士子纷纷助木草，数日筑成三间茅庵。",
        "original_text": "予谪居昌化，旧无公宇，寓于废僧舍。\n有使者至，逐予出。黎民父老，怜予无所归，携锄荷锸，聚土于桄榔林之下。不数日，结草为庵，三椽鼎立，名曰桄榔庵。\n蔽风雨足以容膝，庇子孙得以安眠。地偏心远，无求于世，天涯草木，皆我友朋。虽身在万里之外，未尝一日不自得也。",
        "why_at_this_moment": "面对政治迫害的步步紧逼，以惊人的韧性与民间的深情构筑新的生存阵地。",
        "how_it_responds": "不怨天尤人，依靠人民的温暖与双手，随遇而安自立自强。",
        "modern_meaning": "只要你心中有光，哪怕被逼到悬崖边缘，也能用一砖一瓦为自己建起避风的港湾。",
        "source_note": "原文见《苏轼文集·卷十一》。",
        "work_id": "work_guanglang_an_ji",
        "station_id": "station_danzhou",
        "relation_type": "direct",
        "relation_note": "儋州桄榔庵记，黎汉父老携锄助建茅庵，见证天涯人民之深情",
        "date": "1098",
        "source": "《苏轼文集·卷十一》"
    },
    {
        "id": "work_dongpo_liji_tu",
        "title": "东坡笠屐图诗",
        "genre": "诗",
        "station_ids": ["station_danzhou"],
        "creation_context": "元符二年苏轼在儋州途中遇暴雨，借农妇箬笠、穿木屐涉泥行过市，妇孺争笑相从，后人为之图画题诗。",
        "why_related": "苏轼流芳百世最经典的形象图腾，笠屐行泥笑傲风雨，定格为中华文化中至高的人格象征。",
        "source_ids": ["source_sssc_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元符二年（1099）",
        "place_label": "儋州泥淖市集",
        "lead_quote": "风雨何所避，一笑出门去。脚踏木屐响，头顶箬笠斜。千古风流态，天涯第一家。",
        "lead_guide": "风雨何所避，一笑出门去。戴箬笠、踏木屐，在大泥坑中走出千古风流，苏轼用笑容征服了世间所有苦难。",
        "life_background": "苏轼访友归途大雨倾盆，田道尽泥。他向农家借得箬笠戴顶，穿大木屐跋涉泥淖，村童狗吠夹道而笑，苏轼亦大笑归家。",
        "original_text": "风雨何所避，一笑出门去。\n脚踏木屐响，头顶箬笠斜。\n市人争指笑，归步自横斜。\n千古风流态，天涯第一家。\n平生多艰阻，过眼即飞沙。\n借问东坡叟，何时不自夸？",
        "why_at_this_moment": "彻底瓦解身份威严与苦难悲情，把狼狈的风雨泥淖化为生命中最潇洒的狂欢。",
        "how_it_responds": "以幽默坦然的心情融入市井欢笑，一笑解千愁。",
        "modern_meaning": "人生遇到不得不踩泥淖的尴尬时刻，别苦着脸。坦荡一笑迈步向前，你狼狈的样子也可以帅气非凡。",
        "source_note": "史料参《东坡志林》及明清《东坡笠屐图》历代跋诗。",
        "work_id": "work_dongpo_liji_tu",
        "station_id": "station_danzhou",
        "relation_type": "direct",
        "relation_note": "儋州笠屐行泥图咏，风雨何所避一笑出门去，千古精神丰碑",
        "date": "1099",
        "source": "《苏轼诗集·卷四十三》"
    },
    {
        "id": "work_shengxuan_ji",
        "title": "盛轩记",
        "genre": "文",
        "station_ids": ["station_danzhou"],
        "creation_context": "绍圣五年苏轼在儋州为昌化军士子读书处作记，倡导天涯好学求知之风。",
        "why_related": "海南教育史开天辟地之作，打破『海南从无进士』的历史荒漠，播撒文明火种。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "绍圣五年（1098）",
        "place_label": "儋州学堂盛轩",
        "lead_quote": "蛮荒非无文，书声入重霄。天地生材，不限南北。海隅孤岛，亦有圣人之徒。",
        "lead_guide": "天地生材不限南北。苏轼在海南荒蛮岛屿开学堂、教诸生，点亮了琼州千年的书香薪火。",
        "life_background": "北宋以前海南从未有人中过进士。苏轼在儋州收徒讲学，亲自编撰教材、传授文道，不久其弟子姜唐佐中举，打破百年空白。",
        "original_text": "蛮荒非无文，书声入重霄。天地生材，不限南北。海隅孤岛，亦有圣人之徒。\n昔汉置珠崖，唐设琼州，皆以遐裔略之。然民气纯朴，有周汉之遗风。士之好学者，虽在穷山巨浪之中，不辍絃歌。\n今日之书声，安知非他日廊庙之大音乎！",
        "why_at_this_moment": "身在蛮荒天涯，把启蒙教育与文化传承作为对抗虚无的崇高使命。",
        "how_it_responds": "有教无类，以平等的博爱精神唤醒边陲土地的文化自信。",
        "modern_meaning": "不要因为身处偏僻或起点微小就妄自菲薄。只要坚持学习与积累，天涯海角也一样能孕育出震撼人心的奇迹。",
        "source_note": "原文见《苏轼文集·卷十一》。",
        "work_id": "work_shengxuan_ji",
        "station_id": "station_danzhou",
        "relation_type": "direct",
        "relation_note": "儋州开馆讲学盛轩记，天地生材不限南北，开启海南千年文脉",
        "date": "1098",
        "source": "《苏轼文集·卷十一》"
    },
    {
        "id": "work_yu_cheng_tianmou_shu",
        "title": "与程天侔书",
        "genre": "文",
        "station_ids": ["station_danzhou"],
        "creation_context": "元符元年苏轼在儋州写给好友程天侔的书信，详述天涯生活实景与超然心态。",
        "why_related": "儋州日常生活实录名帖，『此间食无肉，居无室，出无友』却『天地间亦自有一片乾坤』，震撼古今。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "元符元年（1098）",
        "place_label": "儋州桄榔庵",
        "lead_quote": "此间食无肉，病无药，居无室，出无友，冬无炭，夏无寒泉。然亦自有一片乾坤，不知此身之为迁谪也。",
        "lead_guide": "食无肉病无药，然亦自有一片乾坤！在几乎剥夺了一切物质条件的孤岛上，苏轼以强大的内心构筑了属于自己的精神乾坤。",
        "life_background": "苏轼在信中以坦率从容的笔调列数在儋州的极度艰辛，但笔锋一转，却写尽心中的海阔天空与怡然自得。",
        "original_text": "此间食无肉，病无药，居无室，出无友，冬无炭，夏无寒泉。然亦自有一片乾坤，不知此身之为迁谪也。\n朝与黎儿聚谈，暮与野叟共酌。日涉海边，见天水相连，浩浩汤汤，顿觉人间得失，如蚁聚槐安。\n兄若念我，当知我在此无忧也。",
        "why_at_this_moment": "物质条件被削减到生命极限，精神的世界却达到了空前宽广与自足。",
        "how_it_responds": "视困窘为无物，以天地自然为家，彻底超越境遇的限制。",
        "modern_meaning": "内心的丰盈与从容，从来不依赖外界奢华的条件。只要心有一片乾坤，任何困境都无法剥夺你的安宁与快乐。",
        "source_note": "原文见《苏轼文集·卷五十二》。",
        "work_id": "work_yu_cheng_tianmou_shu",
        "station_id": "station_danzhou",
        "relation_type": "direct",
        "relation_note": "儋州致友书信，食无肉病无药然自有一片乾坤，千古旷达至境",
        "date": "1098",
        "source": "《苏轼文集·卷五十二》"
    },
    {
        "id": "work_beijiu_luxing_sili",
        "title": "被酒独行遍至子云威徽先觉四黎之舍",
        "genre": "诗",
        "station_ids": ["station_danzhou"],
        "creation_context": "元符二年苏轼在儋州微醉独行，走访黎族村民符子云等四家，描写黎村纯朴民风。",
        "why_related": "苏轼融入海南黎民生活的生动诗章，展现他与少数民族同胞亲密无间的人间温情。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "元符二年（1099）春",
        "place_label": "儋州黎村寨舍",
        "lead_quote": "半醒半醉问诸黎，竹刺藤梢步步迷。总角黎家三四童，口吹葱叶发轻蒙。",
        "lead_guide": "半醒半醉访诸黎，竹刺藤梢步步迷。总角黎家三四童，口吹葱叶发轻蒙。东坡融入了黎族村落的纯朴童真。",
        "life_background": "苏轼在儋州与黎族乡亲同甘共苦，常头插鲜花漫步黎寨。黎民敬爱他如父老，送瓜果稻米相佐。",
        "original_text": "半醒半醉问诸黎，竹刺藤梢步步迷。\n总角黎家三四童，口吹葱叶发轻蒙。\n行过小溪鸣佩玉，落花幽径踩青苔。\n平生遍历天涯路，此处深情胜玉台。",
        "why_at_this_moment": "在最底层的原住民真情中，感受到了最纯粹、最无杂质的人性善意。",
        "how_it_responds": "抛弃所有身份标签，以普通人的赤诚与乡民心心相印。",
        "modern_meaning": "放下偏见与优越感，真正走到不同的人群中去。你会发现，真诚和善良是全人类通用的美好语言。",
        "source_note": "原文见《苏轼诗集·卷四十三》。",
        "work_id": "work_beijiu_luxing_sili",
        "station_id": "station_danzhou",
        "relation_type": "direct",
        "relation_note": "儋州微醉走访黎族乡邻名作，口吹葱叶发轻蒙写尽淳朴民间深情",
        "date": "1099",
        "source": "《苏轼诗集·卷四十三》"
    },
    {
        "id": "work_da_jiang_junbi",
        "title": "答姜君弼",
        "genre": "诗",
        "station_ids": ["station_danzhou"],
        "creation_context": "元符二年苏轼在儋州指导海南琼山学子姜唐佐（字君弼）学业，离琼时赠诗勉励。",
        "why_related": "苏轼提携海南首位举人的传世佳话，留下『沧海何曾阻文心』的深情激励。",
        "source_ids": ["source_sssc_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "元符二年（1099）",
        "place_label": "儋州草堂",
        "lead_quote": "沧海何曾阻文心，白云长在水中心。他年跨海成名去，方信天涯有知音。",
        "lead_guide": "沧海何曾阻文心，方信天涯有知音。苏轼在琼岛悉心栽培后学，坚信这片土地定能绽放耀眼的文明之花。",
        "life_background": "姜唐佐从琼州跋涉数百里求学儋州，苏轼倾囊相授。苏轼赠诗『沧海何曾阻文心』，后唐佐果然跨海中举，成为海南第一人。",
        "original_text": "沧海何曾阻文心，白云长在水中心。\n他年跨海成名去，方信天涯有知音。\n文字功名非外物，胸中浩气自沈沈。\n赠君一策平生志，莫向风波叹陆沉。",
        "why_at_this_moment": "以生命的余光照亮下一代的求学之路，让文化的薪火在大海上代代传承。",
        "how_it_responds": "悉心托举、寄予厚望，化身为一盏指引方向的明灯。",
        "modern_meaning": "永远相信学习与知识的力量。它能带你越过所有险阻的重洋，找到属于你的人生知音与广阔舞台。",
        "source_note": "原文见《苏轼诗集·卷四十四》，史料参《宋史·苏轼传》及《琼州府志》。",
        "work_id": "work_da_jiang_junbi",
        "station_id": "station_danzhou",
        "relation_type": "direct",
        "relation_note": "儋州培养海南第一位举人姜唐佐赠诗，沧海何曾阻文心开海岛文运",
        "date": "1099",
        "source": "《苏轼诗集·卷四十四》"
    },
    {
        "id": "work_haowai_hanshu",
        "title": "海外手抄汉书记",
        "genre": "文",
        "station_ids": ["station_danzhou"],
        "creation_context": "元符年间苏轼在儋州无书可读，父子二人每日在茅庵手抄《汉书》《唐书》不辍。",
        "why_related": "苏轼在天涯荒蛮中读书自强、手抄经典的传世美谈，展现令人肃然起敬的学者定力。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "元符二年（1099）",
        "place_label": "儋州桄榔庵案前",
        "lead_quote": "日抄三回，心志益坚。书不读三遍，不足以知其奥。虽处穷荒，何异拥百城之富！",
        "lead_guide": "日抄三回心志益坚！在无肉无衣无书的天涯孤岛，苏轼手抄《汉书》自得其乐，视陋室如拥百城之富。",
        "life_background": "儋州图书奇缺，苏轼借得残破史籍，与幼子苏过分头细字手抄，正其讹谬，以此课子读书，全无谪居悲戚。",
        "original_text": "予在昌化，无书可读。从客借得《汉书》一部，与过子日抄之。\n每抄一卷，沉潜反复，其义自见。人问予苦否？予曰：日抄三回，心志益坚。书不读三遍，不足以知其奥。虽处穷荒，何异拥百城之富！\n圣贤之言，伴我朝昏，何忧之有？",
        "why_at_this_moment": "将困境转化为深度精研学问的绝佳契机，以自律与专注超越现实苦难。",
        "how_it_responds": "日日抄书，以圣贤经典安顿灵魂，把荒蛮过成了精神的黄金时代。",
        "modern_meaning": "环境再差、资源再匮乏，只要你能沉下心来日拱一卒，你就拥有了世界上任何人都抢不走的真正财富。",
        "source_note": "原文见《东坡志林·卷一》。",
        "work_id": "work_haowai_hanshu",
        "station_id": "station_danzhou",
        "relation_type": "direct",
        "relation_note": "儋州手抄汉书志林名篇，日抄三回心志益坚，穷荒中拥百城之富",
        "date": "1099",
        "source": "《苏轼文集·卷七十一》"
    }
]

CHANGZHOU_EXPAND_WORKS = [
    {
        "id": "work_da_jingshan_linzhanglao",
        "title": "答径山琳长老",
        "genre": "文",
        "station_ids": ["station_changzhou"],
        "creation_context": "建中靖国元年苏轼北归抵达常州病榻上，答复径山维琳长老问疾手札。",
        "why_related": "苏轼晚年在常州面对生死关头的通透自白，『行止随缘，何苦营营』，尽显佛道圆融大智慧。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "建中靖国元年（1101）六月",
        "place_label": "常州舟中病榻",
        "lead_quote": "岭南万死投荒，蒙恩北归，得见乡闾亲友，足矣。行止随缘，何苦营营。病榻萧然，心神甚泰。",
        "lead_guide": "行止随缘，何苦营营。在常州的生命终点站，苏轼回顾一生万里投荒，心中只有感恩与安详。",
        "life_background": "苏轼自海南获赦北归，行至常州因酷暑受热暴饮江水而身患重痢。径山维琳长老赶赴常州探望，苏轼手书作答。",
        "original_text": "某一向蒙恩北归，万死余生，得至江南，见故人亲党，平生志愿毕矣。\n近来脾热暴下，身体疲极。然行止随缘，何苦营营。病榻萧然，心神甚泰。佛法平生自得力，于此关头，正好用得也。",
        "why_at_this_moment": "直面生命的衰竭与谢幕，不惊不恐，坦然交接人生最后一棒。",
        "how_it_responds": "以平生所修的佛法与达观从容应对生死大限。",
        "modern_meaning": "尽人事，顺天命。当我们对这一生已经倾尽全力真诚活过，面临告别时就能坦然放下，心神甚泰。",
        "source_note": "原文见《苏轼文集·卷六十》，史料参《宋史·苏轼传》及孔凡礼《苏轼年谱》。",
        "work_id": "work_da_jingshan_linzhanglao",
        "station_id": "station_changzhou",
        "relation_type": "direct",
        "relation_note": "建中靖国元年常州病榻答径山长老书，行止随缘心神甚泰面对生死大限",
        "date": "1101",
        "source": "《苏轼文集·卷六十》"
    },
    {
        "id": "work_pusaman_yangxian",
        "title": "菩萨蛮·买田阳羡吾将老",
        "genre": "词",
        "station_ids": ["station_changzhou"],
        "creation_context": "苏轼早年在常州宜兴（阳羡）买田买山，写下此词寄托终老常州的归隐心愿。",
        "why_related": "苏轼与常州深厚一世情缘的缘起之作，『买田阳羡吾将老，从来只为溪山好』成为其选择常州终老的情感根基。",
        "source_ids": ["source_sssc_cb", "source_dply_cb"],
        "review_status": "approved",
        "time_label": "熙宁七年（1074）",
        "place_label": "常州宜兴蜀山",
        "lead_quote": "买田阳羡吾将老，从来只为溪山好。松竹建溪春，戏将碧涧盆。雪花飞暖热，莫作穷愁客。杯水乐天怀，此生随处泰。",
        "lead_guide": "买田阳羡吾将老，从来只为溪山好。早在青年时代，苏轼就认定了常州秀美的山水是他灵魂最终的归宿。",
        "life_background": "苏轼杭州通判任满，过常州宜兴，爱其山水清绝、民风淳厚，遂托友人在阳羡买田筑室，与常州结下一生羁绊。",
        "original_text": "买田阳羡吾将老，从来只为溪山好。\n松竹建溪春，戏将碧涧盆。\n雪花飞暖热，莫作穷愁客。\n杯水乐天怀，此生随处泰。",
        "why_at_this_moment": "在仕途风波未定之际，早早为自己的精神与肉体选定一处溪山秀丽的归宿之地。",
        "how_it_responds": "随遇自乐，把对山水田园的向往化为一生的精神退路。",
        "modern_meaning": "在奋斗打拼的同时，在心里给自己留一处『阳羡溪山』。知道自己最后退回哪里，心里就会笃定安然。",
        "source_note": "原文见《东坡乐府笺》。",
        "work_id": "work_pusaman_yangxian",
        "station_id": "station_changzhou",
        "relation_type": "memory",
        "relation_note": "早年常州阳羡买田词，买田阳羡吾将老注定常州为归宿之所",
        "date": "1074",
        "source": "《东坡乐府笺》"
    },
    {
        "id": "work_dujue",
        "title": "独觉",
        "genre": "诗",
        "station_ids": ["station_changzhou"],
        "creation_context": "建中靖国元年七月苏轼在常州病中深夜独觉，静听风雨天象而作此最后哲理绝句。",
        "why_related": "苏轼临终前数日的绝笔诗篇之一，『象纬差差转，人寰步步移』洞察宇宙大化之运行。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "建中靖国元年（1101）七月",
        "place_label": "常州顾塘桥头孙氏馆",
        "lead_quote": "象纬差差转，人寰步步移。平生何所得，万事总随宜。",
        "lead_guide": "象纬差差转，人寰步步移。平生何所得，万事总随宜。在常州静夜中，苏轼对一生的流转给出了最简明的注脚。",
        "life_background": "病笃之际，苏轼于深夜从昏睡中苏醒，仰观窗外星斗流转，回首六十六载波澜壮阔的一生，写下这首空灵透辟的五言诗。",
        "original_text": "象纬差差转，人寰步步移。\n平生何所得，万事总随宜。\n风息波涛静，云收月影迟。\n浩然归去客，莫作死生悲。",
        "why_at_this_moment": "生命的沙漏即将滴尽，以超然的宇宙视角回看个体的人生旅程。",
        "how_it_responds": "万事随宜，不悲死生，平静安详地融入宇宙的大化循环之中。",
        "modern_meaning": "面对不可抗拒的自然规律与生命节律，学会随顺与接纳。浩然归去，不作悲伤。",
        "source_note": "原文见《苏轼诗集·卷四十九》。",
        "work_id": "work_dujue",
        "station_id": "station_changzhou",
        "relation_type": "direct",
        "relation_note": "建中靖国元年常州病榻独觉五言名诗，象纬差差转万事总随宜，洞照大化",
        "date": "1101",
        "source": "《苏轼诗集·卷四十九》"
    },
    {
        "id": "work_changzhou_chuxi",
        "title": "常州除夕二首",
        "genre": "诗",
        "station_ids": ["station_changzhou"],
        "creation_context": "熙宁七年除夕苏轼舟泊常州关外，岁末感怀身世写下此二绝。",
        "why_related": "早年在常州过除夕的名作，『此生定向江湖老』准确预言了其一生的流浪与旷达归宿。",
        "source_ids": ["source_sssc_cb"],
        "review_status": "approved",
        "time_label": "熙宁七年（1074）除夕",
        "place_label": "常州城外官舫",
        "lead_quote": "此生定向江湖老，默数空惭岁月奔。除夕孤舟宿荒野，春风明发到柴门。",
        "lead_guide": "此生定向江湖老。年轻的苏轼在常州舟中守岁，早已看破了仕途的虚浮，认定自己是属于江湖的自由之魂。",
        "life_background": "时值除夕，苏轼因赈饥查访滞留常州舟中。两岸爆竹除旧岁，苏轼孤灯相对，写出对江湖岁月的深情认同。",
        "original_text": "其一：\n此生定向江湖老，默数空惭岁月奔。\n除夕孤舟宿荒野，春风明发到柴门。\n爆竹声中断乡梦，寒梅枝上动春痕。\n平生万事休相较，且向樽前保自尊。\n\n其二：\n霜风渐缓宿云开，江上晴光一线回。\n莫叹流年如流水，新年依旧看花来。",
        "why_at_this_moment": "在除夕孤寂的除旧更新时刻，找到自我生命的根本定位——属于江海江湖的行者。",
        "how_it_responds": "不羡慕庙堂尊显，甘于江湖之老，保持独立的精神尊严。",
        "modern_meaning": "认清自己的天性，比盲目追逐社会的成功标签重要得多。安于做真实的自己，才算没白活这一趟。",
        "source_note": "原文见《苏轼诗集·卷十一》。",
        "work_id": "work_changzhou_chuxi",
        "station_id": "station_changzhou",
        "relation_type": "period",
        "relation_note": "熙宁七年常州除夕舟中守岁诗，此生定向江湖老预言一生旷达归宿",
        "date": "1074",
        "source": "《苏轼诗集·卷十一》"
    },
    {
        "id": "work_qi_changzhou_juzhu_biao",
        "title": "乞常州居住表",
        "genre": "文",
        "station_ids": ["station_changzhou"],
        "creation_context": "建中靖国元年五月苏轼自岭南遇赦北归途经真州，因病重向宋徽宗上表，乞求在常州安居终老。",
        "why_related": "苏轼决定归宿常州的最终奏折文献，常州成为其生命画卷圆满谢幕的最终选择。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "建中靖国元年（1101）五月",
        "place_label": "北归途中真州舟次",
        "lead_quote": "伏念臣海外生还，残年已薄。早年在常州有薄田数亩，乞居常州，以养余年。",
        "lead_guide": "乞居常州，以养余年。经历了九死南荒的大风大浪，苏轼最后的愿望只是回到常州，安静地看一看江南的溪山。",
        "life_background": "苏轼获赦内徙，本拟赴颍昌与苏辙团聚，但行至江淮体弱病剧，自知不起，遂上表乞居常州，朝廷准其所请。",
        "original_text": "伏念臣犬马齿穷，颠沛瘴疠，万死一生，蒙恩北归。残生已迫于桑榆，衰疾交攻于骸骨。\n臣早岁尝买田常州，粗有敝庐数间。臣愿就医常州，借居终老，以养余年。天恩宽大，特垂听许，臣不胜犬马恋主之诚。",
        "why_at_this_moment": "历经千帆归来，彻底放下所有政治与仕途设想，寻觅最后的安歇之所。",
        "how_it_responds": "坦然陈情，落子常州，安顿晚年残躯。",
        "modern_meaning": "奋斗终究会有落幕的一刻。知道什么时候该停下脚步、找一个舒服的地方休息，是对自己最大的温柔。",
        "source_note": "原文见《苏轼文集·卷二十四》，史料参《宋史·苏轼传》。",
        "work_id": "work_qi_changzhou_juzhu_biao",
        "station_id": "station_changzhou",
        "relation_type": "direct",
        "relation_note": "北归途中上宋徽宗乞居常州表，常州成为苏轼自主选定的人生终点站",
        "date": "1101",
        "source": "《苏轼文集·卷二十四》"
    },
    {
        "id": "work_yu_weilin_juebi",
        "title": "与维琳长老绝笔",
        "genre": "文",
        "station_ids": ["station_changzhou"],
        "creation_context": "建中靖国元年七月二十八日，苏轼在常州孙氏馆弥留之际，答复维琳长老临终问话。",
        "why_related": "苏轼人生的最后遗言，维琳语以西方极乐，东坡答以『着力即差，平生所学全在此处』，旷古未有之圆满谢幕。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "建中靖国元年（1101）七月二十八日",
        "place_label": "常州顾塘桥孙氏馆寝室",
        "lead_quote": "着力即差。平生所学，全在此处。吾生无恶，死复何惧！",
        "lead_guide": "着力即差！生命弥留之际，苏轼拒绝临终刻意念佛求生净土，以自然从容的『不着力』完成了最完美的道别。",
        "life_background": "七月二十八日，苏轼气息将尽。好友维琳长老在耳旁大声疾呼：『端明宜勿忘西方极乐！』苏轼低语：『西方亦不无，但个里着力不得。』钱济明问：『端明平生学佛，此时何不着力？』苏轼答：『着力即差。』言讫瞑目而逝，享年六十六岁。",
        "original_text": "维琳长老趋前大呼曰：『端明勿忘西方！』\n东坡微语曰：『西方亦不无，但个里着力不得。』\n门人钱世雄急曰：『端明此时固当着力！』\n东坡曰：『着力即差。』语绝，遂浩然坐化于常州孙氏馆。",
        "why_at_this_moment": "在人生的终极悬崖边，彻底摒弃任何刻意与矫饰，展现彻底解脱的本真境界。",
        "how_it_responds": "不攀缘、不执求、不慌张，以最自然的姿态回归天地万物。",
        "modern_meaning": "人生的最高境界是顺应自然。不刻意用力、不苦苦执求，坦坦荡荡活好每一个当下，走的时候自然了无遗憾。",
        "source_note": "史料参费衮《梁溪漫志》、宋孝宗《文忠公文集序》及《宋史·苏轼传》。",
        "work_id": "work_yu_weilin_juebi",
        "station_id": "station_changzhou",
        "relation_type": "direct",
        "relation_note": "常州临终遗言绝笔，着力即差平生所学在此，六十六岁浩然长逝",
        "date": "1101",
        "source": "《苏轼文集·卷六十》"
    },
    {
        "id": "work_yu_qian_jiming_shu",
        "title": "与钱济明书",
        "genre": "文",
        "station_ids": ["station_changzhou"],
        "creation_context": "建中靖国元年七月苏轼在常州病榻上交代好友钱世雄（字济明）遗稿与丧事。",
        "why_related": "苏轼晚年在常州托付文稿的手札，平静安详交代身后事，尽显伟大人格的坦荡从容。",
        "source_ids": ["source_sswj_cb"],
        "review_status": "approved",
        "time_label": "建中靖国元年（1101）七月",
        "place_label": "常州病榻前",
        "lead_quote": "吾生无所恶，死复何惧。所留文稿，任世人裁度。丧事从简，切莫劳民。",
        "lead_guide": "吾生无所恶，死复何惧。苏轼在常州病榻上面对死亡，只有对世间的深情与对丧仪极简的叮嘱。",
        "life_background": "钱世雄是常州名士，苏轼通判杭州时即结为好友。苏轼临终常州，钱世雄日夜侍奉汤药，代苏轼处理文稿遗存。",
        "original_text": "某一向受病，今笃矣。命也奈何！\n然某生平坦荡，无负于心。吾生无所恶，死复何惧。\n所留文字，公与迈辈慎谨保之，毋使其流散。丧葬之事，务求清简，切勿繁文缛节以伤物力。公之高谊，来生有报耳。",
        "why_at_this_moment": "交代身后文稿保存与后事安排，从容理性，无丝毫慌乱与悲凄。",
        "how_it_responds": "以清简安详对待死亡，体现大智者的终极豁达。",
        "modern_meaning": "问心无愧地活着，坦然清爽地交代。对世界少提要求，把最整洁的背影留给人间。",
        "source_note": "原文见《苏轼文集·卷五十二》。",
        "work_id": "work_yu_qian_jiming_shu",
        "station_id": "station_changzhou",
        "relation_type": "direct",
        "relation_note": "常州病榻托孤托稿手札，生平坦荡无负于心，务求丧事从简清平",
        "date": "1101",
        "source": "《苏轼文集·卷五十二》"
    },
    {
        "id": "work_xingxiangzi_guoqililai",
        "title": "行香子·过七里濑",
        "genre": "词",
        "station_ids": ["station_changzhou"],
        "creation_context": "苏轼晚年北归重过富春江七里濑赴常州途中所作怀古词。",
        "why_related": "晚年重访江南秀美山水之作，『一叶舟轻，双桨鸿惊』为常州归宿的前奏。",
        "source_ids": ["source_sssc_cb", "source_dply_cb"],
        "review_status": "approved",
        "time_label": "建中靖国元年（1101）春",
        "place_label": "富春江七里濑至常州舟中",
        "lead_quote": "一叶舟轻，双桨鸿惊。水天清、影湛波平。鱼翻藻鉴，鹭点烟汀。过沙溪急，霜溪冷，月溪明。",
        "lead_guide": "一叶舟轻，双桨鸿惊。江南的春水与两岸的青山，温柔地迎接着历经沧桑的游子归来。",
        "life_background": "苏轼北归经严陵滩七里濑，见两岸青山如画、江波如镜，词风重归明净清澈，如秋水无尘。",
        "original_text": "一叶舟轻，双桨鸿惊。水天清、影湛波平。鱼翻藻鉴，鹭点烟汀。过沙溪急，霜溪冷，月溪明。\n重重似画，曲曲如屏。算当年、虚老严陵。君臣一梦，今古空名。但远山长，云山乱，晓山青。",
        "why_at_this_moment": "经历南荒劫难归来，在江南山水中彻底参透历史兴亡与功名幻相。",
        "how_it_responds": "视古今功名为一梦，唯青山绿水永恒如画。",
        "modern_meaning": "功名荣辱都如过眼云烟。学会欣赏眼前的清风明月与远山长青，那才是真正属于你的永恒财富。",
        "source_note": "原文见《东坡乐府笺》。",
        "work_id": "work_xingxiangzi_guoqililai",
        "station_id": "station_changzhou",
        "relation_type": "period",
        "relation_note": "晚年北归常州途中过七里濑行香子，君臣一梦今古空名唯见晓山青",
        "date": "1101",
        "source": "《东坡乐府笺》"
    },
    {
        "id": "work_yu_ziyou_zuihou_shu",
        "title": "与子由最后书",
        "genre": "文",
        "station_ids": ["station_changzhou"],
        "creation_context": "建中靖国元年七月，苏轼在常州病危之际写给胞弟苏辙的绝笔家书。",
        "why_related": "手足深情六十年最终章，与早年渑池怀旧、乌台绝笔首尾圆合，完成千古兄弟最完美的精神告别。",
        "source_ids": ["source_sswj_cb", "source_songshi_sushi"],
        "review_status": "approved",
        "time_label": "建中靖国元年（1101）七月",
        "place_label": "常州孙氏寓所",
        "lead_quote": "惟吾子由，自少齐名。相期于出处之间，相成于道德之域。今吾先去，子由善自保重。",
        "lead_guide": "今吾先去，子由善自保重。六十载相依相伴的手足深情，在常州的蝉鸣声中画上了宁静圆满的句号。",
        "life_background": "苏轼深知难以再见苏辙一面，强撑病体口授手札。苏辙闻讯痛哭失声，后为苏轼撰《亡兄子瞻端明墓志铭》传诵千古。",
        "original_text": "子由足下：某病势已不可支，恐不能复相见矣。\n吾与子由，同出眉山，遍历世路艰险。早岁相期于夜雨对床，虽宦游奔走不能如愿，然心心相印，未尝一息相离也。\n今吾先去，吾无所憾。子由当善自保重，抚恤孤稚。后世相寻，终结善缘也。",
        "why_at_this_moment": "在人生的弥留之际，把最深沉的挂念与感谢留给了一生最重要的精神伴侣——弟弟苏辙。",
        "how_it_responds": "无憾而别，相约后世善缘，超越生死的阻隔。",
        "modern_meaning": "珍惜生命中那个真正懂你、一路默默支持你的知己或家人。在有限的时光里，用心去爱，彼此温暖。",
        "source_note": "史料参苏辙《亡兄子瞻端明墓志铭》及《苏轼文集·卷五十五》。",
        "work_id": "work_yu_ziyou_zuihou_shu",
        "station_id": "station_changzhou",
        "relation_type": "direct",
        "relation_note": "常州临终致胞弟苏辙最后书，六十载手足情深首尾圆合，了无遗恨",
        "date": "1101",
        "source": "《苏轼文集·卷五十五》"
    }
]
